/**
 * ÚNICO ponto de tradução en → pt-BR (D6).
 *
 * Código, schema e rotas ficam em inglês; todo texto visível ao usuário sai daqui.
 * Nenhum componente ou Server Action escreve string em pt-BR diretamente.
 *
 * Formato:
 * - `labels`      textos de interface agrupados por área (app, common, ui...).
 * - `enumLabels`  rótulo de cada valor de enum do domínio, por grupo. Cada fase
 *                 que cria um enum no schema acrescenta o grupo correspondente aqui.
 * - `enumLabel()` leitura tipada de `enumLabels`.
 * - `fill()`      interpolação de `{chave}` em textos com valores.
 */

export const labels = {
  app: {
    name: "Prontuário",
    description: "Registro de gestão do time de suporte",
  },
  common: {
    save: "Salvar",
    cancel: "Cancelar",
    close: "Fechar",
    confirm: "Confirmar",
    retry: "Tentar novamente",
    loading: "Carregando",
    search: "Buscar",
    select: "Selecionar",
    noResults: "Nenhum resultado",
    optional: "opcional",
    required: "obrigatório",
    previousMonth: "Mês anterior",
    nextMonth: "Próximo mês",
  },
  nav: {
    today: "Hoje",
    team: "Equipe",
    agreements: "Combinados",
    priorityValidations: "Validação de prioridade",
    dailies: "Dailies",
    records: "Registros",
    development: "Desenvolvimento",
    settings: "Configurações",
    timeline: "Timeline",
  },
  shell: {
    skipToContent: "Pular para o conteúdo",
    mainNavigation: "Navegação principal",
    openNavigation: "Abrir navegação",
    collapseSidebar: "Recolher barra lateral",
    expandSidebar: "Expandir barra lateral",
    breadcrumb: "Você está em",
    searchPlaceholder: "Buscar pessoa, combinado ou ação",
    searchShortcut: "⌘K",
  },
  auth: {
    explanation: "Registro de gestão do time de suporte. Acesso restrito.",
    email: "E-mail",
    password: "Senha",
    submit: "Entrar",
    /** Idêntico para e-mail inexistente, senha errada e conta bloqueada (CLAUDE.md). */
    invalidCredentials: "E-mail ou senha inválidos",
    signOut: "Sair",
    currentUser: "Usuário atual",
    readOnly: "Somente leitura",
    readOnlyHint: "Seu acesso é de leitura. Registros privados do gestor não aparecem para você.",
  },
  access: {
    forbidden: "Ação não permitida para o seu papel.",
  },
  validation: {
    required: "Campo obrigatório.",
    tooShort: "Texto curto demais.",
    tooLong: "Texto longo demais.",
    email: "E-mail inválido.",
    date: "Data inválida. Use DD/MM/AAAA.",
    futureDate: "A data não pode ser no futuro.",
    pastDueDate: "O prazo não pode estar no passado.",
    beforeRecordDate: "Precisa ser depois da data do registro.",
    minutes: "Informe os minutos, de 1 a 999.",
    reasonRequired: "Informe o motivo: mudança de senioridade, cargo ou status é evento de carreira.",
    generic: "Não foi possível salvar. Revise os campos.",
  },
  team: {
    tableLabel: "Pessoas do time",
    peopleCount: "{count} pessoas",
    personCount: "1 pessoa",
    columns: {
      person: "Pessoa",
      seniority: "Senioridade",
      tenure: "No time",
      status: "Status",
      lastOneOnOne: "Último 1:1",
      openAgreements: "Combinados abertos",
      attention: "Atenção",
      actions: "Ações",
    },
    filters: {
      button: "Filtros",
      seniority: "Senioridade",
      allSeniorities: "Todas",
      status: "Status",
      current: "Ativos e afastados",
      inactive: "Inativos",
      needsAttention: "Precisa de atenção",
      groupBySeniority: "Agrupar por senioridade",
      clear: "Limpar filtros",
    },
    empty: {
      filteredTitle: "Ninguém com esses filtros",
      filteredDirection: "Ajuste ou limpe os filtros da barra de contexto para ver o time inteiro.",
    },
    noOneOnOne: "Nenhum",
    noAttention: "Sem pendências",
    add: "Adicionar pessoa",
    edit: "Editar cadastro",
    deactivate: "Desativar pessoa",
    rowActions: "Ações de {name}",
    form: {
      createTitle: "Adicionar pessoa",
      createDescription: "Cadastro de quem entra no time. Responsabilidades e competências são opcionais.",
      editTitle: "Editar cadastro",
      editDescription: "Mudança de senioridade, cargo ou status vira evento de carreira, com motivo.",
      fullName: "Nome completo",
      preferredName: "Nome preferido",
      preferredNameHelp: "Como a pessoa é chamada no dia a dia. Aparece nas listas.",
      position: "Cargo",
      seniority: "Senioridade",
      joinedAt: "Data de entrada",
      joinedAtPlaceholder: "DD/MM/AAAA",
      status: "Status",
      email: "E-mail",
      moreDetails: "Mais detalhes",
      lessDetails: "Menos detalhes",
      responsibilities: "Responsabilidades",
      responsibilitiesHelp: "Marque as que a pessoa assume a partir de hoje.",
      competencies: "Competências avaliadas",
      competenciesHelp: "Nível atual de 1 a 5. Deixe em branco o que não foi avaliado.",
      notAssessed: "—",
      reason: "Motivo da mudança",
      reasonHelp: "Fica registrado na timeline da pessoa.",
      careerChange: "Esta edição muda {fields}. Isso gera um evento de carreira.",
      fieldSeniority: "senioridade",
      fieldPosition: "cargo",
      fieldStatus: "status",
      save: "Salvar",
      create: "Adicionar pessoa",
    },
    deactivateDialog: {
      title: "Desativar {name}?",
      description:
        "A pessoa sai das listagens ativas. Nada é apagado: 1:1, feedbacks, combinados e timeline continuam no histórico.",
      reason: "Motivo da saída",
      confirm: "Desativar pessoa",
    },
  },
  attention: {
    overdue: { one: "1 combinado vencido há {days} dias", other: "{count} combinados vencidos; o mais antigo há {days} dias" },
    dueSoon: { one: "1 combinado vence em até {limit} dias", other: "{count} combinados vencem em até {limit} dias" },
    chronic: {
      one: "1 combinado reagendado {limit} vezes ou mais",
      other: "{count} combinados reagendados {limit} vezes ou mais",
    },
    noOneOnOne: "Nenhum 1:1 registrado desde a entrada, há {days} dias",
    lateOneOnOne: "Sem 1:1 há {days} dias (referência para {seniority}: {limit} dias)",
    stalePlan: "PDI sem acompanhamento há {days} dias",
  },
  timeline: {
    /** Título da linha de 1:1 quando não há assuntos registrados. */
    oneOnOneFallback: "1:1",
    /** Resumo da revisão de combinados de uma pessoa na daily. */
    dailyReview: { one: "Revisão de 1 combinado: {detail}", other: "Revisão de {count} combinados: {detail}" },
    dailyReviewParts: { done: "{count} feito", doneMany: "{count} feitos", partial: "{count} parcial", partialMany: "{count} parciais", notDone: "{count} não feito", notDoneMany: "{count} não feitos" },
    /** Título de mudança de carreira: "Pleno → Sênior". */
    memberChange: "{from} → {to}",
    label: "Timeline de {name}",
    filters: {
      types: "Tipos",
      allTypes: "Todos os tipos",
      typesCount: "{count} tipos",
      clearTypes: "Mostrar todos",
      period: "Período",
      search: "Buscar nesta timeline",
      clear: "Limpar filtros",
    },
    periods: {
      "30d": "30 dias",
      "3m": "3 meses",
      "6m": "6 meses",
      all: "Tudo",
    },
    loadMore: "Carregar mais",
    end: "Início do histórico",
    expand: "Mostrar tudo",
    collapse: "Mostrar menos",
    by: "por {name}",
    private: "Privado",
    shared: "Compartilhado",
    makeShared: "Compartilhar",
    makePrivate: "Tornar privado",
    sharedByModel: "Combinados, dailies, PDIs e mudanças de carreira não têm visibilidade própria: quem tem acesso de leitura sempre vê.",
    shareDialog: {
      title: "Compartilhar este registro?",
      description:
        "Quem tem acesso de leitura passa a ver este registro e o conteúdo completo dele. Você pode tornar privado de novo depois.",
      confirm: "Compartilhar registro",
    },
    agreementLink: "Combinado",
    linkedAgreements: { one: "Gerou 1 combinado", other: "Gerou {count} combinados" },
    due: "prazo",
    reviewDue: "Revisão marcada para {date}",
    stalePlan: "PDI sem acompanhamento há {days} dias",
    emptyTitle: "Nenhum registro ainda",
    emptyDirection: "1:1, feedbacks, combinados, dailies e anotações desta pessoa aparecem aqui, do mais recente para o mais antigo.",
    filteredTitle: "Nenhum registro com esses filtros",
    filteredDirection: "Amplie o período, marque mais tipos ou limpe a busca.",
    loadError: "Não foi possível carregar mais registros.",
    /** Tags gravadas em inglês (origem, categoria, tipo de mudança) → rótulo. */
    tags: {
      daily: "daily",
      one_on_one: "1:1",
      feedback: "feedback",
      meeting: "reunião",
      incident: "ocorrência",
      manager: "gestor",
      other: "outra",
      impeditivo: "impeditivo",
      recognition: "reconhecimento",
      development: "desenvolvimento",
      behavior: "comportamento",
      technical: "técnico",
      performance: "desempenho",
      formal: "formal",
      seniority: "senioridade",
      position: "cargo",
      status: "status",
      responsibility: "responsabilidade",
    } as Record<string, string>,
  },
  profile: {
    fields: {
      joinedAt: "Entrada",
      manager: "Gestor",
      lastOneOnOne: "Último 1:1",
      nextFollowUp: "Próximo acompanhamento",
      responsibilities: "Responsabilidades",
    },
    none: "Nenhum",
    noneScheduled: "Nenhum agendado",
    followUpKind: {
      oneOnOne: "revisão do 1:1",
      feedback: "follow-up de feedback",
    },
    attention: "Atenção",
    inactive: "Pessoa inativa desde {date}. O histórico continua disponível para leitura.",
    actions: {
      oneOnOne: "Registrar 1:1",
      feedback: "Dar feedback",
      agreement: "Novo combinado",
      note: "Anotação",
      edit: "Editar cadastro",
      deactivate: "Desativar pessoa",
      record: "Registrar",
      more: "Mais ações",
    },
    tabs: {
      label: "Seções do perfil",
      overview: "Visão geral",
      timeline: "Timeline",
      agreements: "Combinados",
      development: "Desenvolvimento",
      records: "1:1 e feedbacks",
    },
    summary: {
      title: "Resumo gerencial",
      emptyTitle: "Sem resumo ainda",
      emptyDirection: "Duas ou três frases sobre o momento da pessoa: o que vai bem, o que preocupa e qual é o próximo passo.",
      emptyViewer: "O gestor ainda não escreveu um resumo desta pessoa.",
      write: "Escrever resumo",
      edit: "Editar resumo",
      save: "Salvar resumo",
      fieldLabel: "Resumo gerencial",
      hint: "Ctrl+Enter salva · Esc cancela",
      visibleToViewer: "Visível também para quem tem acesso de leitura.",
    },
    recent: {
      title: "Últimos registros",
      all: "Ver timeline completa",
      emptyTitle: "Nenhum registro ainda",
      emptyDirection: "1:1, feedbacks, combinados e anotações aparecem aqui assim que forem registrados.",
      private: "Privado",
      shared: "Compartilhado",
    },
    traits: {
      strengths: "Pontos fortes",
      development: "Pontos de desenvolvimento",
      emptyStrengths: "Nenhum ponto forte ativo",
      emptyDevelopment: "Nenhum ponto de desenvolvimento ativo",
      emptyDirection: "Pontos observados entram pela aba Desenvolvimento.",
    },
    agreements: {
      title: "Combinados em aberto",
      all: "Ver todos",
      emptyTitle: "Nenhum combinado em aberto",
      emptyDirection: "Combinados criados em dailies, 1:1 ou aqui no perfil aparecem com prazo e severidade.",
      rescheduled: { one: "reagendado 1 vez", other: "reagendado {count} vezes" },
    },
    plans: {
      title: "PDIs ativos",
      emptyTitle: "Nenhum PDI ativo",
      emptyDirection: "Planos ativos aparecem com o andamento das ações e a data do último acompanhamento.",
      progress: "{done} de {total} ações concluídas",
      noActions: "Sem ações definidas",
      lastReview: { one: "Acompanhado há 1 dia", other: "Acompanhado há {count} dias" },
      reviewedToday: "Acompanhado hoje",
      neverReviewed: "Sem acompanhamento desde o início, há {days} dias",
    },
    mentorship: {
      title: "Mentorias",
      mentoredBy: "Mentorada por",
      mentors: "Mentora",
      since: "desde",
      general: "Geral",
      emptyTitle: "Nenhuma mentoria ativa",
      emptyDirection: "Vínculos de mentoria entre pessoas do time aparecem aqui, com a competência e a data de início.",
    },
    rhythm: {
      title: "Ritmo",
      oneOnOne: "Desde o último 1:1",
      feedback: "Desde o último feedback",
      anyRecord: "Desde o último registro",
      daysAgo: { one: "1 dia", other: "{count} dias" },
      today: "hoje",
      never: "nenhum",
      reference: "referência {limit} dias",
    },
    pendingTab: {
      development: {
        title: "Desenvolvimento ainda não disponível",
        direction: "PDIs ativos, pontos fortes e de desenvolvimento aparecem na visão geral.",
      },
      records: {
        title: "Histórico de 1:1 e feedbacks ainda não disponível",
        direction: "Registre 1:1 e feedbacks pelo cabeçalho do perfil; eles já entram nos últimos registros da visão geral.",
      },
    },
  },
  agreements: {
    tableLabel: "Combinados",
    count: { one: "1 combinado", other: "{count} combinados" },
    views: {
      label: "Visualização",
      overdue: "Atrasados",
      dueSoon: "Vencendo (7 dias)",
      open: "Em aberto",
      done: "Concluídos",
      all: "Todos",
    },
    columns: {
      title: "Combinado",
      member: "Responsável",
      origin: "Origem",
      createdAt: "Criado em",
      dueDate: "Prazo",
      priority: "Prioridade",
      status: "Status",
      drag: "Arrasto",
      actions: "Ações",
    },
    filters: {
      button: "Filtros",
      member: "Pessoa",
      allMembers: "Todas as pessoas",
      seniority: "Senioridade",
      allSeniorities: "Todas",
      origin: "Origem",
      allOrigins: "Todas",
      priority: "Prioridade",
      allPriorities: "Todas",
      created: "Criado nos últimos",
      allTime: "Qualquer data",
      clear: "Limpar filtros",
    },
    created: { "30d": "30 dias", "3m": "3 meses", "6m": "6 meses", all: "Qualquer data" },
    drag: { one: "reagendado 1x", other: "reagendado {count}x" },
    dragged: "arrastado {count}x",
    rowActions: "Ações do combinado",
    open: "Abrir combinado",
    complete: "Marcar como concluído",
    new: "Novo combinado",
    newShortcut: "C",
    emptyByView: {
      overdue: "Nenhum combinado atrasado",
      dueSoon: "Nada vencendo nos próximos 7 dias",
      open: "Nenhum combinado em aberto",
      done: "Nenhum combinado concluído",
      all: "Nenhum combinado registrado",
    },
    emptyDirection: "Combinados nascem em dailies, 1:1, feedbacks ou pelo atalho C em qualquer tela.",
    filteredDirection: "Ajuste ou limpe os filtros para ver mais combinados.",
    completeDialog: {
      title: "Concluir combinado",
      description: "Registre em uma linha o que foi entregue. Opcional, mas é o que dá sentido ao histórico.",
      outcome: "Resultado",
      outcomePlaceholder: "Ex.: macro revisada e publicada na base",
      confirm: "Marcar como concluído",
    },
    detail: {
      responsible: "Responsável",
      origin: "Origem",
      sourceDaily: "Daily de {date}",
      createdAt: "Criado em",
      originalDueDate: "Prazo original",
      dueDate: "Prazo atual",
      priority: "Prioridade",
      completedAt: "Concluído em",
      outcome: "Resultado",
      description: "Detalhes",
      replaces: "Substitui",
      replacedBy: "Substituído por",
      author: "Registrado por",
      checkins: "Revisões nas dailies",
      checkinsEmpty: "Ainda não foi revisado em nenhuma daily",
      checkinsEmptyDirection: "Cada revisão numa daily entra aqui com o desfecho, o impeditivo e o novo prazo, quando houver.",
      checkinColumns: { date: "Daily", outcome: "Desfecho", blocker: "Impeditivo", newDueDate: "Novo prazo" },
      noBlocker: "—",
      dragSummary: "Prazo movido {count} vezes desde {date}",
    },
    alreadyClosed: "Este combinado já está encerrado.",
  },
  dailies: {
    new: "Registrar daily",
    newTitle: "Daily de {date}",
    newSubtitle: "Revise os combinados, anote o que cada pessoa trouxe e registre os combinados de hoje.",
    date: "Data da daily",
    save: "Salvar daily",
    saveHint: "Ctrl+Enter salva tudo",
    forbidden: "Só quem escreve registra dailies.",
    review: {
      title: "Revisão dos combinados",
      direction: "Criados na daily anterior e em aberto com prazo até hoje.",
      emptyTitle: "Nada para revisar hoje",
      emptyDirection: "A daily anterior não gerou combinados e nenhum combinado em aberto vence até hoje.",
      outcomes: "Desfecho",
      done: "Feito",
      partial: "Parcial",
      notDone: "Não feito",
      keyHint: "F feito · P parcial · N não feito · setas trocam",
      undo: "Desfazer",
      blocker: "Impeditivo",
      blockerPlaceholder: "O que impediu, em uma linha",
      reason: "Motivo",
      reasonNone: "Sem motivo",
      action: "O que fazer com o combinado",
      reschedule: "Reagendar",
      replace: "Substituir por novo combinado",
      newDueDate: "Novo prazo",
      replacementTitle: "Novo combinado",
      replacementDueDate: "Prazo",
      fromPreviousDaily: "da daily anterior",
      due: "prazo",
    },
    participants: {
      title: "Participantes e notas",
      direction: "Todos presentes por padrão. Tab passa de uma pessoa para a próxima.",
      keyHint: "Alt+A marca ausente · Alt+B marca a nota como bloqueio",
      present: "Presente",
      absent: "Ausente",
      notePlaceholder: "Nota de {name}",
      blocker: "Bloqueio",
      markBlocker: "Marcar como bloqueio",
      unmarkBlocker: "Desmarcar bloqueio",
      count: "{present} de {total} presentes",
    },
    newAgreements: {
      title: "Combinados de hoje",
      direction: "Enter acrescenta outra linha. A daily de amanhã revisa estes combinados.",
      member: "Responsável",
      memberPlaceholder: "Pessoa",
      agreementTitle: "Combinado",
      dueDate: "Prazo",
      add: "Adicionar linha",
      remove: "Remover linha",
    },
    extra: {
      toggle: "Resumo e decisões",
      summary: "Resumo geral",
      decisions: "Decisões",
    },
    draft: {
      restored: "Rascunho restaurado ({time}). O que estava preenchido voltou.",
      discard: "Descartar rascunho",
      saved: "Rascunho salvo às {time}",
    },
    validation: {
      blockerRequired: "Descreva o impeditivo.",
      futureDue: "O novo prazo precisa ser depois da daily.",
      notBeforeDaily: "O prazo não pode ser antes da daily.",
      replacementRequired: "Informe o novo combinado.",
      agreementClosed: "Um dos combinados revisados já foi encerrado em outra tela. Recarregue a página.",
      rowIncomplete: "Preencha responsável, combinado e prazo, ou deixe a linha vazia.",
    },
    whatsapp: {
      copy: "Copiar para WhatsApp",
      copied: "Copiado",
      failed: "Não foi possível copiar",
    },
    history: {
      tableLabel: "Dailies registradas",
      count: { one: "1 daily", other: "{count} dailies" },
      present: "presentes",
      blockers: { one: "1 bloqueio", other: "{count} bloqueios" },
      reviewed: { one: "1 revisado", other: "{count} revisados" },
      created: { one: "1 criado", other: "{count} criados" },
      expand: "Ver detalhe",
      collapse: "Recolher",
      open: "Abrir daily",
      emptyTitle: "Nenhuma daily registrada",
      emptyDirection: "Ao registrar uma daily, os combinados da anterior e os vencidos entram para revisão automaticamente.",
    },
    detail: {
      reviewed: "Combinados revisados",
      created: "Combinados criados",
      notes: "Notas",
      absent: "Ausentes",
      summary: "Resumo geral",
      decisions: "Decisões",
      replacedBy: "substituído por",
      newDue: "novo prazo",
      author: "Registrada por {name}",
      none: "Nada registrado",
    },
  },
  forms: {
    date: "Data",
    datePlaceholder: "DD/MM/AAAA",
    visibility: "Visibilidade",
    visibilityHelp: {
      PRIVATE: "Só você vê.",
      SHARED: "Quem tem acesso de leitura também vê.",
    },
    oneOnOne: {
      title: "Registrar 1:1",
      description: "Com {name}. Nasce privado.",
      topics: "Assuntos tratados",
      duration: "Duração (min)",
      perceptions: "Percepções",
      memberPerception: "Percepção do colaborador",
      managerPerception: "Percepção do gestor",
      progress: "Conquistas e dificuldades",
      wins: "Conquistas",
      difficulties: "Dificuldades",
      next: "Desenvolvimento e próxima revisão",
      development: "Desenvolvimento",
      nextReviewAt: "Próxima revisão",
      submit: "Registrar 1:1",
    },
    feedback: {
      title: "Dar feedback",
      description: "Para {name}. Contexto, comportamento e impacto, nessa ordem.",
      category: "Categoria",
      context: "Contexto",
      contextHelp: "Quando e onde aconteceu.",
      behavior: "Comportamento observado",
      behaviorHelp: "O que a pessoa fez, específico e sem interpretação.",
      impact: "Impacto",
      impactHelp: "O efeito no cliente, no time ou no resultado.",
      guidance: "Orientação",
      guidanceHelp: "O que fica combinado daqui pra frente.",
      followUpAt: "Follow-up",
      recognitionHint: "Reconhecimento sugere compartilhar. Você pode manter privado.",
      submit: "Registrar feedback",
    },
    note: {
      title: "Anotação",
      description: "Sobre {name}. Nasce privada.",
      noteTitle: "Título",
      body: "Anotação",
      submit: "Salvar anotação",
    },
    agreement: {
      title: "Novo combinado",
      description: "Com {name}. Só o que foi combinado e o prazo são obrigatórios.",
      agreementTitle: "O que foi combinado",
      member: "Responsável",
      memberPlaceholder: "Selecione a pessoa",
      descriptionGeneral: "Só o que foi combinado, o responsável e o prazo são obrigatórios.",
      dueDate: "Prazo",
      details: "Detalhes",
      priority: "Prioridade",
      origin: "Origem",
      shortcut: "Enter salva · Ctrl+Enter salva e abre outro",
      submit: "Criar combinado",
      savedAnother: "Combinado criado. Pode lançar o próximo.",
    },
  },
  notFound: {
    title: "Página não encontrada",
    direction: "Este endereço não corresponde a nenhuma página do Prontuário. Confira o link ou volte para Hoje.",
    action: "Ir para Hoje",
  },
  pages: {
    today: {
      subtitle: "Quem precisa da sua atenção hoje.",
      emptyTitle: "Nenhum alerta por enquanto",
      emptyDirection:
        "Combinados vencidos, 1:1 atrasados, PDIs parados e dailies não registradas aparecem aqui, ordenados por urgência, assim que houver registros do time.",
    },
    team: {
      subtitle: "Cadastro das pessoas do time, com senioridade, último 1:1 e combinados em aberto.",
      emptyTitle: "Nenhuma pessoa cadastrada",
      emptyDirection:
        "Cada analista cadastrado ganha um perfil com timeline, combinados, 1:1, feedbacks e plano de desenvolvimento.",
    },
    agreements: {
      subtitle: "Compromissos combinados com o time, com responsável, prazo e histórico de reagendamento.",
      emptyTitle: "Nenhum combinado registrado",
      emptyDirection:
        "Combinados nascem em dailies, 1:1 e feedbacks e aparecem aqui com o prazo original, o prazo atual e quantas vezes foram reagendados.",
    },
    priorityValidations: {
      subtitle: "Prioridade definida pelo analista no chamado e prioridade confirmada pela supervisão.",
      emptyTitle: "Nenhuma validação registrada",
      emptyDirection:
        "Cada validação registra o chamado, o responsável, as duas prioridades e se ela foi mantida, elevada, reduzida ou devolvida para reanálise.",
    },
    dailies: {
      subtitle: "Revisão dos combinados do dia anterior e registro dos novos, por pessoa.",
      emptyTitle: "Nenhuma daily registrada",
      emptyDirection:
        "Ao registrar uma daily, os combinados da anterior e os vencidos entram para revisão automaticamente.",
    },
    records: {
      subtitle: "1:1 e feedbacks de todo o time.",
      emptyTitle: "Nenhum 1:1 ou feedback registrado",
      emptyDirection:
        "1:1 e feedbacks ficam aqui, filtráveis por pessoa, tipo e período. Nascem privados; só o feedback de reconhecimento sugere compartilhar com o gestor.",
    },
    development: {
      subtitle: "Planos de desenvolvimento, competências e acompanhamentos.",
      emptyTitle: "Nenhum plano de desenvolvimento ativo",
      emptyDirection:
        "Planos aparecem aqui com a data do último acompanhamento. Plano sem acompanhamento há mais de 45 dias fica em destaque.",
    },
    settings: {
      subtitle: "Parâmetros que alimentam registros e alertas.",
      emptyTitle: "Nenhum parâmetro cadastrado",
      emptyDirection:
        "Aqui ficam os níveis de prioridade, os motivos de bloqueio e de reclassificação, os padrões de URL de chamado e os limiares dos alertas.",
    },
  },
  command: {
    title: "Paleta de comandos",
    description: "Busque uma ação ou um registro",
    placeholder: "Buscar ação ou registro",
  },
  table: {
    loading: "Carregando registros",
    errorTitle: "Não foi possível carregar os registros",
    emptyTitle: "Nenhum registro",
    selectedRow: "Linha selecionada",
  },
  severity: {
    /** Degrau "laranja" da escala graduada (attention + strong). */
    attentionStrong: "Atenção forte",
  },
  deadline: {
    noDueDate: "Sem prazo",
    onTrack: "Em dia",
    dueToday: "Vence hoje",
    dueInDays: "Vence em {days} dias",
    dueTomorrow: "Vence amanhã",
    overdueOneDay: "Vencido há 1 dia",
    overdueDays: "Vencido há {days} dias",
    probablyForgotten: "Provavelmente esquecido",
  },
  sparkline: {
    summary: "{count} pontos, de {first} a {last}",
    empty: "Sem dados no período",
  },
  uiLab: {
    title: "UI Lab",
    subtitle: "Referência visual obrigatória. Todo componente novo nasce aqui antes de entrar numa tela.",
    states: {
      default: "Padrão",
      hover: "Hover",
      focus: "Foco",
      selected: "Selecionado",
      disabled: "Desabilitado",
      loading: "Carregando",
      empty: "Vazio",
      error: "Erro",
      compact: "Compacto",
    },
  },
} as const;

export const enumLabels = {
  memberStatus: {
    ACTIVE: "Ativo",
    ON_LEAVE: "Afastado",
    OFFBOARDING: "Em desligamento",
    INACTIVE: "Inativo",
  },
  role: {
    OWNER: "Gestor",
    MANAGER: "Gestor de time",
    VIEWER: "Leitura",
  },
  visibility: {
    PRIVATE: "Privado",
    SHARED: "Compartilhado",
  },
  feedbackCategory: {
    RECOGNITION: "Reconhecimento",
    DEVELOPMENT: "Desenvolvimento",
    BEHAVIOR: "Comportamento",
    TECHNICAL: "Técnico",
    PERFORMANCE: "Desempenho",
    FORMAL: "Formal",
  },
  agreementOrigin: {
    DAILY: "Daily",
    ONE_ON_ONE: "1:1",
    FEEDBACK: "Feedback",
    MEETING: "Reunião",
    INCIDENT: "Ocorrência",
    MANAGER: "Gestor",
    OTHER: "Outra",
  },
  agreementPriority: {
    LOW: "Baixa",
    NORMAL: "Normal",
    HIGH: "Alta",
  },
  checkinOutcome: {
    DONE: "Feito",
    PARTIAL: "Parcial",
    NOT_DONE: "Não feito",
  },
  blockerCategory: {
    EXTERNAL: "Externo",
    INTERNAL: "Interno",
    CAPACITY: "Capacidade",
  },
  agreementStatus: {
    OPEN: "Aberto",
    IN_PROGRESS: "Em andamento",
    DONE: "Concluído",
    CANCELLED: "Cancelado",
  },
  /** Etiqueta mono do tipo de registro na timeline (DESIGN.md). */
  timelineEventType: {
    DAILY: "Daily",
    FEEDBACK: "Feedback",
    ONE_ON_ONE: "1:1",
    RECOGNITION: "Reconhecimento",
    INCIDENT: "Ocorrência",
    AGREEMENT: "Combinado",
    AGREEMENT_DONE: "Concluído",
    ROLE_CHANGE: "Carreira",
    SENIORITY_CHANGE: "Senioridade",
    DEVELOPMENT: "PDI",
    NOTE: "Anotação",
  },
  severity: {
    calm: "Em dia",
    attention: "Atenção",
    overdue: "Vencido",
    neutral: "Aberto",
  },
} as const;

type EnumLabels = typeof enumLabels;

export function enumLabel<G extends keyof EnumLabels>(
  group: G,
  value: keyof EnumLabels[G],
): string {
  return enumLabels[group][value] as string;
}

/** Substitui `{chave}` pelos valores informados: fill("Vence em {days} dias", { days: 3 }). */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}

/** Escolhe singular ou plural e interpola: plural(labels.attention.overdue, 2, { days: 9 }). */
export function plural(
  forms: { one: string; other: string },
  count: number,
  values: Record<string, string | number> = {},
): string {
  return fill(count === 1 ? forms.one : forms.other, { count, ...values })
}
