/**
 * ÚNICO ponto de tradução en → pt-BR (D6).
 *
 * Código, schema e rotas ficam em inglês; todo texto visível ao usuário sai daqui.
 * Nenhum componente ou Server Action escreve string em pt-BR diretamente.
 *
 * Formato:
 * - `labels`      textos de interface agrupados por área (app, common, ui...).
 * - `enumLabels`  rótulo de cada valor de enum do domínio, por grupo. Cada fase
 *                 que cria um enum no schema acrescenta o grupo correspondente aqui.
 * - `enumLabel()` leitura tipada de `enumLabels`.
 * - `fill()`      interpolação de `{chave}` em textos com valores.
 */

export const labels = {
  app: {
    name: "Prontuário",
    description: "Registro de gestão do time de suporte",
  },
  common: {
    save: "Salvar",
    cancel: "Cancelar",
    close: "Fechar",
    confirm: "Confirmar",
    retry: "Tentar novamente",
    loading: "Carregando",
    search: "Buscar",
    select: "Selecionar",
    noResults: "Nenhum resultado",
    optional: "opcional",
    required: "obrigatório",
    previousMonth: "Mês anterior",
    nextMonth: "Próximo mês",
    desktopHint: "Formulário longo: a experiência é melhor no computador, mas funciona aqui também.",
  },
  toast: {
    region: "Avisos",
    dismiss: "Fechar aviso",
    oneOnOneCreated: "1:1 registrado",
    feedbackCreated: "Feedback registrado",
    noteCreated: "Anotação registrada",
    recordUpdated: "Alterações salvas",
    recordDeleted: "Registro excluído",
    memberSaved: "Cadastro salvo",
    memberDeactivated: "Pessoa desativada",
    memberReactivated: "Pessoa reativada",
    planCreated: "PDI criado",
    planUpdated: "PDI atualizado",
    planReviewed: "Acompanhamento registrado",
    actionAdded: "Ação acrescentada",
    mentorshipCreated: "Mentoria registrada",
    mentorshipEnded: "Mentoria encerrada",
    agreementCompleted: "Combinado concluído",
    agreementCancelled: "Combinado cancelado",
    agreementUpdated: "Combinado atualizado",
    dailyUpdated: "Daily atualizada",
    scoreCreated: "Definição criada",
    scoreVersion: "Versão nova criada",
    scoreActivated: "Versão ativada",
    scoreDeactivated: "Versão desativada",
    scoreDeleted: "Rascunho excluído",
    componentSaved: "Composição salva",
  },
  nav: {
    today: "Hoje",
    watch: "Em observação",
    team: "Equipe",
    agreements: "Combinados",
    priorityValidations: "Validação de prioridade",
    dailies: "Dailies",
    records: "Registros",
    development: "Desenvolvimento",
    settings: "Configurações",
    timeline: "Timeline",
  },
  shell: {
    skipToContent: "Pular para o conteúdo",
    mainNavigation: "Navegação principal",
    openNavigation: "Abrir navegação",
    collapseSidebar: "Recolher barra lateral",
    expandSidebar: "Expandir barra lateral",
    breadcrumb: "Você está em",
    searchPlaceholder: "Buscar pessoa, combinado ou ação",
    searchShortcut: "⌘K",
  },
  auth: {
    explanation: "Registro de gestão do time de suporte. Acesso restrito.",
    email: "E-mail",
    password: "Senha",
    submit: "Entrar",
    /** Idêntico para e-mail inexistente, senha errada e conta bloqueada (CLAUDE.md). */
    invalidCredentials: "E-mail ou senha inválidos",
    signOut: "Sair",
    currentUser: "Usuário atual",
    readOnly: "Somente leitura",
    readOnlyHint: "Seu acesso é de leitura. Registros privados do gestor não aparecem para você.",
  },
  access: {
    forbidden: "Ação não permitida para o seu acesso neste time.",
    noTeamAccess: "Você não tem acesso a este time.",
    noTeams: "Sua conta não tem acesso a nenhum time. Fale com o administrador.",
    selectTeam: "Escolha o time que você quer abrir.",
    moduleDisabled: "Este módulo não está ligado neste time.",
  },
  validation: {
    required: "Campo obrigatório.",
    tooShort: "Texto curto demais.",
    tooLong: "Texto longo demais.",
    email: "E-mail inválido.",
    date: "Data inválida. Use DD/MM/AAAA.",
    futureDate: "A data não pode ser no futuro.",
    pastDueDate: "O prazo não pode estar no passado.",
    beforeRecordDate: "Precisa ser depois da data do registro.",
    minutes: "Informe os minutos, de 1 a 999.",
    reasonRequired: "Informe o motivo: mudança de senioridade, cargo ou status é evento de carreira.",
    generic: "Não foi possível salvar. Revise os campos.",
  },
  team: {
    tableLabel: "Pessoas do time",
    peopleCount: "{count} pessoas",
    personCount: "1 pessoa",
    columns: {
      person: "Pessoa",
      seniority: "Senioridade",
      tenure: "No time",
      status: "Status",
      lastOneOnOne: "Último 1:1",
      openAgreements: "Combinados abertos",
      attention: "Atenção",
      actions: "Ações",
    },
    filters: {
      button: "Filtros",
      seniority: "Senioridade",
      allSeniorities: "Todas",
      status: "Status",
      current: "Ativos e afastados",
      inactive: "Inativos",
      needsAttention: "Precisa de atenção",
      groupBySeniority: "Agrupar por senioridade",
      clear: "Limpar filtros",
    },
    empty: {
      filteredTitle: "Ninguém com esses filtros",
      filteredDirection: "Ajuste ou limpe os filtros da barra de contexto para ver o time inteiro.",
    },
    noOneOnOne: "Nenhum",
    noAttention: "Sem pendências",
    add: "Adicionar pessoa",
    edit: "Editar cadastro",
    deactivate: "Desativar pessoa",
    rowActions: "Ações de {name}",
    form: {
      createTitle: "Adicionar pessoa",
      createDescription: "Cadastro de quem entra no time. Responsabilidades e competências são opcionais.",
      editTitle: "Editar cadastro",
      editDescription: "Mudança de senioridade, cargo ou status vira evento de carreira, com motivo.",
      fullName: "Nome completo",
      preferredName: "Nome preferido",
      preferredNameHelp: "Como a pessoa é chamada no dia a dia. Aparece nas listas.",
      position: "Cargo",
      seniority: "Senioridade",
      joinedAt: "Data de entrada",
      joinedAtPlaceholder: "DD/MM/AAAA",
      status: "Status",
      email: "E-mail",
      moreDetails: "Mais detalhes",
      lessDetails: "Menos detalhes",
      responsibilities: "Responsabilidades",
      responsibilitiesHelp: "Marque as que a pessoa assume a partir de hoje.",
      competencies: "Competências avaliadas",
      competenciesHelp: "Nível atual de 1 a 5. Deixe em branco o que não foi avaliado.",
      notAssessed: "—",
      reason: "Motivo da mudança",
      reasonHelp: "Fica registrado na timeline da pessoa.",
      careerChange: "Esta edição muda {fields}. Isso gera um evento de carreira.",
      fieldSeniority: "senioridade",
      fieldPosition: "cargo",
      fieldStatus: "status",
      save: "Salvar",
      create: "Adicionar pessoa",
    },
    deactivateDialog: {
      title: "Desativar {name}?",
      description:
        "A pessoa sai das listagens ativas. Nada é apagado: 1:1, feedbacks, combinados e timeline continuam no histórico.",
      reason: "Motivo da saída",
      confirm: "Desativar pessoa",
    },
    reactivate: "Reativar",
    reactivateDialog: {
      title: "Reativar {name}?",
      description: "A pessoa volta às listagens e aos alertas como ativa. A mudança entra na timeline como evento de carreira.",
      reason: "Motivo do retorno",
      confirm: "Reativar pessoa",
    },
  },
  today: {
    title: "Hoje",
    date: "{weekday}, {date}",
    actionsLabel: "Registrar",
    actions: {
      daily: "Registrar daily",
      agreement: "Novo combinado",
      validation: "Validar prioridade",
      oneOnOne: "Registrar 1:1",
      feedback: "Dar feedback",
    },
    pickMember: {
      title: "Com quem?",
      description: "Escolha a pessoa. O formulário abre em seguida.",
      label: "Pessoa",
      placeholder: "Escolha a pessoa",
      next: "Continuar",
    },
    needsYou: "Precisa de você",
    needsYouDirection: "Ordenado por urgência: o mais vencido primeiro.",
    listLabel: "Alertas de hoje, do mais urgente ao menos urgente",
    team: "Time",
    emptyTitle: "Nada vencido hoje",
    emptyDirection: "Nenhum combinado vencido, 1:1 atrasado, PDI parado, follow-up pendente ou daily em falta.",
    noTeam: "Cadastre as pessoas do time para os alertas começarem a aparecer.",
    informativeHeading: "Informativo",
    composition: "Composição do time",
    compositionLabel: "{count} pessoas: {parts}",
    compositionPart: "{count} {label}",
    onLeave: { one: "1 afastada", other: "{count} afastadas" },
    rhythm: "Ritmo de gestão",
    rhythmItems: {
      lastDaily: "Desde a última daily",
      oneOnOnes: "1:1 no mês",
      feedbacks: "Feedbacks no mês",
      adherence: "Cumprimento no mês",
      watch: "Em observação",
    },
    rhythmWatchDetail: { one: "1 fogo alto", other: "{count} fogo alto" },
    rhythmDays: { one: "1 dia", other: "{count} dias" },
    rhythmDailyToday: "hoje",
    rhythmNoDaily: "nunca",
    rhythmAdherenceDetail: "{onTime} de {total} no prazo",
    rhythmAdherenceSmall: "amostra pequena",
    rhythmAdherenceNone: "nenhum devido",
    upcoming: "Próximos acompanhamentos",
    upcomingDirection: "Próximos 7 dias: combinados, revisões de 1:1, follow-ups e prazos de PDI.",
    upcomingEmpty: "Nada marcado para os próximos 7 dias.",
    upcomingMore: { one: "e mais 1 nos próximos 7 dias", other: "e mais {count} nos próximos 7 dias" },
    upcomingKinds: {
      agreement: "Combinado",
      review: "Revisão do 1:1",
      followUp: "Follow-up",
      plan: "Prazo do PDI",
      action: "Ação do PDI",
    },
    recent: "Últimas movimentações",
    recentEmpty: "Nenhum registro ainda.",
    seeTimeline: "Ver timeline",
    alerts: {
      overdue: "Combinado vencido: \u201c{title}\u201d",
      overdueChronic: "Combinado vencido e reagendado {count}x: \u201c{title}\u201d",
      chronic: "Combinado reagendado {count}x, ainda em aberto: \u201c{title}\u201d",
      dueSoon: {
        one: "1 combinado vence nos próximos {limit} dias",
        other: "{count} combinados vencem nos próximos {limit} dias",
      },
      lateOneOnOne: "Sem 1:1 além da referência de {seniority} ({limit} dias)",
      noOneOnOne: "Nenhum 1:1 desde a entrada (referência de {seniority}: {limit} dias)",
      silence: "Nenhum registro de qualquer tipo: 1:1, feedback, anotação ou combinado",
      silenceNever: "Nenhum registro desde a entrada",
      stalePlan: "PDI sem acompanhamento: \u201c{objective}\u201d",
      stalePlanNever: "PDI nunca acompanhado: \u201c{objective}\u201d",
      followUp: "Follow-up de feedback sem conversa depois: \u201c{behavior}\u201d",
      dailyMissing: {
        one: "Nenhuma daily no último dia útil",
        other: "Nenhuma daily nos últimos {count} dias úteis",
      },
      dailyNever: "Nenhuma daily registrada ainda",
      readiness: "Atende ao nível esperado de {seniority} em todas as {total} competências",
      watchUnreviewed: "Sem revisão: \u201c{title}\u201d ({heat}, revisar a cada {cadence} dias)",
      watchColdHigh: "\u201c{title}\u201d: fogo alto há {days} dias sem mudar de grau",
      watchStalled: "Em observação e nunca revisada: \u201c{title}\u201d",
      watchNoMember: "Sem pessoa",
      devReturnsRecurring: "{count} devoluções do desenvolvimento pelo mesmo motivo em {days} dias: \u201c{reason}\u201d",
      devReturnUnresolved: "Chamado {ref} devolvido pelo desenvolvimento e ainda não reenviado",
      ageToday: "hoje",
      ageDays: { one: "há 1 dia", other: "há {count} dias" },
      lateDays: { one: "vencido há 1 dia", other: "vencido há {count} dias" },
      last30: "últimos 30 dias",
      informative: "informativo",
      actions: {
        openAgreement: "Abrir combinado",
        seeAgreements: "Ver combinados",
        oneOnOne: "Registrar 1:1",
        feedback: "Dar feedback",
        reviewPlan: "Acompanhar PDI",
        daily: "Registrar daily",
        seeAdherence: "Ver cumprimento",
        seeDevelopment: "Ver desenvolvimento",
        seeDevReturns: "Ver devoluções",
        openWatch: "Abrir observação",
      },
    },
    counters: "{count} pedindo atenção",
  },
  attention: {
    overdue: { one: "1 combinado vencido há {days} dias", other: "{count} combinados vencidos; o mais antigo há {days} dias" },
    dueSoon: { one: "1 combinado vence em até {limit} dias", other: "{count} combinados vencem em até {limit} dias" },
    chronic: {
      one: "1 combinado reagendado {limit} vezes ou mais",
      other: "{count} combinados reagendados {limit} vezes ou mais",
    },
    noOneOnOne: "Nenhum 1:1 registrado desde a entrada, há {days} dias",
    lateOneOnOne: "Sem 1:1 há {days} dias (referência para {seniority}: {limit} dias)",
    stalePlan: "PDI sem acompanhamento há {days} dias",
    adherenceDrop:
      "Cumprimento no prazo caiu de {previous}% para {current}% ({previousTotal} e {currentTotal} combinados: 30 dias anteriores e últimos 30)",
  },
  timeline: {
    /** Título da linha de 1:1 quando não há assuntos registrados. */
    oneOnOneFallback: "1:1",
    planReview: "Acompanhamento do PDI: {objective}",
    planDone: "PDI concluído: {objective}",
    /** Resumo da revisão de combinados de uma pessoa na daily. */
    dailyReview: { one: "Revisão de 1 combinado: {detail}", other: "Revisão de {count} combinados: {detail}" },
    dailyReviewParts: { done: "{count} feito", doneMany: "{count} feitos", partial: "{count} parcial", partialMany: "{count} parciais", notDone: "{count} não feito", notDoneMany: "{count} não feitos" },
    /** Título de mudança de carreira: "Pleno → Sênior". */
    memberChange: "{from} → {to}",
    label: "Timeline de {name}",
    filters: {
      types: "Tipos",
      allTypes: "Todos os tipos",
      typesCount: "{count} tipos",
      clearTypes: "Mostrar todos",
      period: "Período",
      search: "Buscar nesta timeline",
      clear: "Limpar filtros",
    },
    periods: {
      "30d": "30 dias",
      "3m": "3 meses",
      "6m": "6 meses",
      all: "Tudo",
    },
    loadMore: "Carregar mais",
    end: "Início do histórico",
    expand: "Mostrar tudo",
    collapse: "Mostrar menos",
    by: "por {name}",
    private: "Privado",
    shared: "Compartilhado",
    makeShared: "Compartilhar",
    makePrivate: "Tornar privado",
    sharedByModel: "Combinados, dailies, PDIs e mudanças de carreira não têm visibilidade própria: quem tem acesso de leitura sempre vê.",
    shareDialog: {
      title: "Compartilhar este registro?",
      description:
        "Quem tem acesso de leitura passa a ver este registro e o conteúdo completo dele. Você pode tornar privado de novo depois.",
      confirm: "Compartilhar registro",
    },
    agreementLink: "Combinado",
    linkedAgreements: { one: "Gerou 1 combinado", other: "Gerou {count} combinados" },
    due: "prazo",
    reviewDue: "Revisão marcada para {date}",
    stalePlan: "PDI sem acompanhamento há {days} dias",
    emptyTitle: "Nenhum registro ainda",
    emptyDirection: "1:1, feedbacks, combinados, dailies e anotações desta pessoa aparecem aqui, do mais recente para o mais antigo.",
    filteredTitle: "Nenhum registro com esses filtros",
    filteredDirection: "Amplie o período, marque mais tipos ou limpe a busca.",
    loadError: "Não foi possível carregar mais registros.",
    /** Tags gravadas em inglês (origem, categoria, tipo de mudança) → rótulo. */
    tags: {
      daily: "daily",
      one_on_one: "1:1",
      feedback: "feedback",
      meeting: "reunião",
      incident: "ocorrência",
      manager: "gestor",
      other: "outra",
      impeditivo: "impeditivo",
      resolved: "resolvida",
      recognition: "reconhecimento",
      development: "desenvolvimento",
      behavior: "comportamento",
      technical: "técnico",
      performance: "desempenho",
      formal: "formal",
      seniority: "senioridade",
      position: "cargo",
      status: "status",
      responsibility: "responsabilidade",
      acompanhamento: "acompanhamento",
      concluido: "concluído",
    } as Record<string, string>,
  },
  profile: {
    fields: {
      joinedAt: "Entrada",
      manager: "Gestor",
      lastOneOnOne: "Último 1:1",
      nextFollowUp: "Próximo acompanhamento",
      responsibilities: "Responsabilidades",
    },
    none: "Nenhum",
    noneScheduled: "Nenhum agendado",
    followUpKind: {
      oneOnOne: "revisão do 1:1",
      feedback: "follow-up de feedback",
    },
    attention: "Atenção",
    inactive: "Pessoa inativa desde {date}. O histórico continua disponível para leitura.",
    actions: {
      oneOnOne: "Registrar 1:1",
      feedback: "Dar feedback",
      agreement: "Novo combinado",
      note: "Anotação",
      edit: "Editar cadastro",
      deactivate: "Desativar pessoa",
      record: "Registrar",
      more: "Mais ações",
    },
    tabs: {
      label: "Seções do perfil",
      overview: "Visão geral",
      timeline: "Timeline",
      agreements: "Combinados",
      development: "Desenvolvimento",
      records: "1:1 e feedbacks",
    },
    summary: {
      title: "Resumo gerencial",
      emptyTitle: "Sem resumo ainda",
      emptyDirection: "Duas ou três frases sobre o momento da pessoa: o que vai bem, o que preocupa e qual é o próximo passo.",
      emptyViewer: "O gestor ainda não escreveu um resumo desta pessoa.",
      write: "Escrever resumo",
      edit: "Editar resumo",
      save: "Salvar resumo",
      fieldLabel: "Resumo gerencial",
      hint: "Ctrl+Enter salva · Esc cancela",
      visibleToViewer: "Visível também para quem tem acesso de leitura.",
    },
    recent: {
      title: "Últimos registros",
      all: "Ver timeline completa",
      emptyTitle: "Nenhum registro ainda",
      emptyDirection: "1:1, feedbacks, combinados e anotações aparecem aqui assim que forem registrados.",
      private: "Privado",
      shared: "Compartilhado",
    },
    traits: {
      strengths: "Pontos fortes",
      development: "Pontos de desenvolvimento",
      emptyStrengths: "Nenhum ponto forte ativo",
      emptyDevelopment: "Nenhum ponto de desenvolvimento ativo",
      emptyDirection: "Pontos observados entram pela aba Desenvolvimento.",
    },
    agreements: {
      title: "Combinados em aberto",
      all: "Ver todos",
      emptyTitle: "Nenhum combinado em aberto",
      emptyDirection: "Combinados criados em dailies, 1:1 ou aqui no perfil aparecem com prazo e severidade.",
      rescheduled: { one: "reagendado 1 vez", other: "reagendado {count} vezes" },
    },
    plans: {
      title: "PDIs ativos",
      emptyTitle: "Nenhum PDI ativo",
      emptyDirection: "Planos ativos aparecem com o andamento das ações e a data do último acompanhamento.",
      progress: "{done} de {total} ações concluídas",
      noActions: "Sem ações definidas",
      lastReview: { one: "Acompanhado há 1 dia", other: "Acompanhado há {count} dias" },
      reviewedToday: "Acompanhado hoje",
      neverReviewed: "Sem acompanhamento desde o início, há {days} dias",
    },
    mentorship: {
      title: "Mentorias",
      mentoredBy: "Mentorada por",
      mentors: "Mentora",
      since: "desde",
      general: "Geral",
      emptyTitle: "Nenhuma mentoria ativa",
      emptyDirection: "Vínculos de mentoria entre pessoas do time aparecem aqui, com a competência e a data de início.",
    },
    rhythm: {
      title: "Ritmo",
      oneOnOne: "Desde o último 1:1",
      feedback: "Desde o último feedback",
      anyRecord: "Desde o último registro",
      daysAgo: { one: "1 dia", other: "{count} dias" },
      today: "hoje",
      never: "nenhum",
      reference: "referência {limit} dias",
    },
  },
  agreements: {
    tableLabel: "Combinados",
    count: { one: "1 combinado", other: "{count} combinados" },
    views: {
      label: "Visualização",
      overdue: "Atrasados",
      dueSoon: "Vencendo (7 dias)",
      open: "Em aberto",
      done: "Concluídos",
      all: "Todos",
    },
    columns: {
      title: "Combinado",
      member: "Responsável",
      origin: "Origem",
      createdAt: "Criado em",
      dueDate: "Prazo",
      priority: "Prioridade",
      status: "Status",
      drag: "Arrasto",
      actions: "Ações",
    },
    filters: {
      button: "Filtros",
      member: "Pessoa",
      allMembers: "Todas as pessoas",
      seniority: "Senioridade",
      allSeniorities: "Todas",
      origin: "Origem",
      allOrigins: "Todas",
      priority: "Prioridade",
      allPriorities: "Todas",
      created: "Criado nos últimos",
      allTime: "Qualquer data",
      clear: "Limpar filtros",
    },
    created: { "30d": "30 dias", "3m": "3 meses", "6m": "6 meses", all: "Qualquer data" },
    drag: { one: "reagendado 1x", other: "reagendado {count}x" },
    dragged: "arrastado {count}x",
    rowActions: "Ações do combinado",
    open: "Abrir combinado",
    complete: "Marcar como concluído",
    edit: "Editar",
    cancel: "Cancelar combinado",
    showMore: "Mostrar mais {count}",
    showing: "{shown} de {total}",
    new: "Novo combinado",
    newShortcut: "C",
    emptyByView: {
      overdue: "Nenhum combinado atrasado",
      dueSoon: "Nada vencendo nos próximos 7 dias",
      open: "Nenhum combinado em aberto",
      done: "Nenhum combinado concluído",
      all: "Nenhum combinado registrado",
    },
    emptyDirection: "Combinados nascem em dailies, 1:1, feedbacks ou pelo atalho C em qualquer tela.",
    filteredDirection: "Ajuste ou limpe os filtros para ver mais combinados.",
    completeDialog: {
      title: "Concluir combinado",
      description: "Registre em uma linha o que foi entregue. Opcional, mas é o que dá sentido ao histórico.",
      outcome: "Resultado",
      outcomePlaceholder: "Ex.: macro revisada e publicada na base",
      confirm: "Marcar como concluído",
    },
    cancelDialog: {
      title: "Cancelar combinado",
      description:
        "O combinado sai das listas em aberto e não volta para a daily. Ele continua no histórico, com o motivo. Para trocar por outro, use Substituir na daily.",
      reason: "Motivo do cancelamento",
      reasonPlaceholder: "Ex.: o cliente desistiu da integração",
      keep: "Manter combinado",
      confirm: "Cancelar combinado",
    },
    editDialog: {
      title: "Editar combinado",
      description: "Texto e prioridade. A timeline acompanha a edição.",
      dueDateHint: "Prazo e responsável não mudam aqui: o prazo se move na daily, onde o reagendamento fica registrado.",
      submit: "Salvar alterações",
    },
    detail: {
      responsible: "Responsável",
      origin: "Origem",
      sourceDaily: "Daily de {date}",
      createdAt: "Criado em",
      originalDueDate: "Prazo original",
      dueDate: "Prazo atual",
      priority: "Prioridade",
      completedAt: "Concluído em",
      outcome: "Resultado",
      cancelReason: "Motivo do cancelamento",
      description: "Detalhes",
      replaces: "Substitui",
      replacedBy: "Substituído por",
      author: "Registrado por",
      checkins: "Revisões nas dailies",
      checkinsEmpty: "Ainda não foi revisado em nenhuma daily",
      checkinsEmptyDirection: "Cada revisão numa daily entra aqui com o desfecho, o impeditivo e o novo prazo, quando houver.",
      checkinColumns: { date: "Daily", outcome: "Desfecho", blocker: "Impeditivo", newDueDate: "Novo prazo" },
      noBlocker: "—",
      dragSummary: "Prazo movido {count} vezes desde {date}",
    },
    alreadyClosed: "Este combinado já está encerrado.",
  },
  adherence: {
    title: "Cumprimento de combinados",
    teamSubtitle: "{from} a {to}. Prazo original de cada combinado; nenhuma taxa sem o total ao lado.",
    profileTitle: "Cumprimento — últimos {days} dias",
    overviewTitle: "Cumprimento de combinados",
    window: "Últimos {days} dias",
    seeDetails: "Ver cumprimento",
    seeTeam: "Cumprimento do time",
    onTime: "No prazo",
    late: "Com atraso",
    openOverdue: "Em aberto vencidos",
    rate: "Cumprimento no prazo",
    adjusted: "Ajustada (excluindo bloqueio externo)",
    adjustedInline: "ajustada (excluindo bloqueio externo): {rate}",
    agreements: { one: "1 combinado", other: "{count} combinados" },
    agreementsParen: { one: "(1 combinado)", other: "({count} combinados)" },
    lowConfidence: "amostra pequena",
    lowConfidenceHelp: "Menos de {min} combinados: a taxa existe, mas diz pouco. Não entra na média do time.",
    noData: "Nenhum combinado venceu no período.",
    monthly: "Taxa mensal, últimos {months} meses",
    currentMonth: "Mês corrente: {value}",
    currentMonthNone: "Mês corrente: nenhum combinado venceu ainda",
    chronic: {
      one: "1 combinado arrastado {limit} vezes ou mais:",
      other: "{count} combinados arrastados {limit} vezes ou mais:",
    },
    blockers: "Impeditivos no período",
    blockersNone: "Nenhum impeditivo registrado no período.",
    blockerNoReason: "Sem motivo registrado",
    blockersCount: { one: "1 revisão", other: "{count} revisões" },
    trend: "Tendência",
    trendHelp: "Últimos 30 dias contra os 30 anteriores, em pontos percentuais.",
    trendValue: "{previous}% → {current}%",
    trendUp: "subiu {delta} pontos",
    trendDown: "caiu {delta} pontos",
    trendFlat: "estável",
    trendInsufficient: "amostra pequena para tendência",
    pp: "{delta} p.p.",
    columns: {
      member: "Pessoa",
      seniority: "Senioridade",
      total: "Combinados",
      onTime: "No prazo",
      rate: "Taxa bruta",
      adjusted: "Taxa ajustada",
      drag: "Arrasto médio",
      trend: "Tendência",
      actions: "Ações",
    },
    tableLabel: "Cumprimento por pessoa",
    dragValue: "{value}x",
    feedback: "Registrar feedback",
    feedbackFor: "Registrar feedback para {name}",
    suggestion:
      "Cumprimento de combinados de {from} a {to}: {onTime} de {total} no prazo ({rate}). Ajustada, excluindo bloqueio externo: {adjusted}.{trend}",
    suggestionTrend: " Últimos 30 dias contra os 30 anteriores: {previous}% → {current}%.",
    teamLine: "{total} no período · taxa do time {rate} · impeditivo mais frequente: {blocker}",
    teamRate: "{rate}% ({onTime} de {total})",
    teamRateNone: "sem pessoas com amostra suficiente",
    teamExcluded: { one: "1 pessoa com menos de {min} combinados fica fora da taxa do time", other: "{count} pessoas com menos de {min} combinados ficam fora da taxa do time" },
    teamBlockerNone: "nenhum",
    periods: { "30d": "30 dias", "90d": "90 dias", "6m": "6 meses", "12m": "12 meses", custom: "Personalizado" },
    sort: "Ordenar por",
    sorts: { name: "Nome", rate: "Taxa bruta" },
    emptyTitle: "Nenhuma pessoa no time",
    emptyDirection: "O cumprimento aparece aqui assim que houver combinados com prazo no período.",
  },
  records: {
    title: "1:1 e feedbacks",
    subtitle: "Índice dos registros do time. Nascem privados; o VIEWER vê só os compartilhados.",
    count: { one: "1 registro", other: "{count} registros" },
    tableLabel: "1:1 e feedbacks",
    columns: {
      date: "Data",
      type: "Tipo",
      member: "Pessoa",
      summary: "Registro",
      category: "Categoria",
      followUp: "Follow-up",
      agreements: "Combinados",
      visibility: "Visibilidade",
    },
    types: { oneOnOne: "1:1", feedback: "Feedback" },
    filters: {
      button: "Filtros",
      type: "Tipo",
      allTypes: "Todos",
      member: "Pessoa",
      allMembers: "Todas",
      category: "Categoria",
      allCategories: "Todas",
      period: "Período",
      clear: "Limpar filtros",
    },
    periods: { "30d": "30 dias", "3m": "3 meses", "6m": "6 meses", "12m": "12 meses", all: "Tudo" },
    followUp: {
      none: "—",
      done: "Feito em {date}",
      doneTitle: "Encerrado pela conversa de {date}",
    },
    emptyTitle: "Nenhum 1:1 ou feedback no período",
    emptyDirection: "Registre 1:1 e feedbacks pelo perfil de cada pessoa. Eles aparecem aqui, com o follow-up.",
    filteredDirection: "Ajuste ou limpe os filtros para ver mais registros.",
    detail: {
      open: "Abrir registro",
      by: "Registrado por {name}",
      duration: "{minutes} min",
      timeline: "Ver na timeline",
      agreements: "Combinados gerados",
    },
    newOneOnOne: "Registrar 1:1",
    newFeedback: "Dar feedback",
  },
  development: {
    title: "Desenvolvimento",
    subtitle: "PDIs, competências, mentorias e prontidão. Nada aqui é nota: nenhuma tela ordena pessoas por desempenho.",
    plans: {
      title: "PDIs",
      active: "Ativos",
      others: "Rascunhos, pausados e encerrados",
      new: "Novo PDI",
      empty: "Nenhum PDI registrado",
      emptyDirection: "Um PDI parte de uma situação atual, um objetivo e as ações com responsável e prazo.",
      competency: "Competência",
      noCompetency: "Sem competência vinculada",
      currentSituation: "Situação atual",
      objective: "Objetivo",
      expectedEvidence: "Evidência esperada",
      progressNote: "Último acompanhamento",
      startedAt: "Início",
      dueDate: "Prazo",
      actions: "Ações",
      noActions: "Nenhuma ação definida.",
      progress: "{done} de {total} ações concluídas",
      lastReview: "Acompanhado em {date}",
      lastReviewAgo: { one: "sem acompanhamento há 1 dia", other: "sem acompanhamento há {count} dias" },
      neverReviewed: { one: "nunca acompanhado · iniciado há 1 dia", other: "nunca acompanhado · iniciado há {count} dias" },
      stale: "PDI parado",
      review: "Registrar acompanhamento",
      statusMenu: "Mais ações do PDI",
      edit: "Editar PDI",
      addAction: "Acrescentar ação",
      setStatus: { ACTIVE: "Ativar", PAUSED: "Pausar", DONE: "Concluir", CANCELLED: "Cancelar PDI", DRAFT: "Voltar a rascunho" },
      owner: { MEMBER: "Pessoa", MANAGER: "Gestor", MENTOR: "Mentor" },
      ownerWithName: "Mentor: {name}",
      actionDone: "Marcar ação {description} como concluída",
      actionReopen: "Reabrir ação {description}",
      noDue: "sem prazo",
    },
    planDialog: {
      title: "Novo PDI",
      description: "Para {name}. Situação atual, objetivo e ações com responsável e prazo.",
      competencyPlaceholder: "Escolha a competência",
      noCompetency: "Nenhuma",
      status: "Começa como",
      statusOptions: { ACTIVE: "Ativo", DRAFT: "Rascunho" },
      actions: "Ações",
      actionDescription: "Ação",
      actionOwner: "Responsável",
      actionMentor: "Mentor",
      actionMentorPlaceholder: "Pessoa",
      actionDue: "Prazo",
      addAction: "Adicionar ação",
      removeAction: "Remover ação",
      submit: "Criar PDI",
      editTitle: "Editar PDI",
      editDescription: "De {name}. Início, status e ações seguem pelo próprio PDI.",
    },
    actionDialog: {
      title: "Acrescentar ação",
      description: "Ao PDI \u201c{objective}\u201d.",
      submit: "Acrescentar ação",
    },
    reviewDialog: {
      title: "Registrar acompanhamento",
      description: "O que mudou desde o último acompanhamento. Entra na timeline e zera o relógio do PDI.",
      note: "Acompanhamento",
      notePlaceholder: "Ex.: concluiu o módulo de logs; falta acompanhar dois plantões",
      submit: "Registrar acompanhamento",
    },
    statusDialog: {
      title: "{action}",
      description: "O PDI \u201c{objective}\u201d passa para {status}.",
      confirm: "{action}",
      keep: "Manter como está",
    },
    competencies: {
      title: "Competências",
      direction: "Nível atual de 1 a 5, contra o esperado da senioridade atual e da próxima. A matriz é definida em Configurações.",
      level: "Nível {level} de 5",
      notAssessed: "não avaliada",
      expected: "esperado {seniority}: {level}",
      noExpectation: "sem nível esperado definido",
      assessedAt: "avaliada em {date}",
      empty: "Nenhuma competência avaliada",
      emptyDirection: "Os níveis de cada pessoa são registrados em Editar cadastro.",
      matrixEmpty: "A matriz de níveis esperados ainda não foi preenchida.",
      matrixLink: "Preencher em Configurações",
    },
    traits: {
      title: "Pontos fortes e de desenvolvimento",
      strengths: "Pontos fortes",
      developmentPoints: "Pontos de desenvolvimento",
      archived: "Histórico",
      observedAt: "observado em {date}",
      add: "Registrar ponto",
      archive: "Arquivar",
      archiveLabel: "Arquivar {text}",
      empty: "Nenhum registrado.",
      dialogTitle: "Registrar ponto",
      dialogDescription: "Para {name}. Um comportamento observado, com a data em que foi observado.",
      kind: "Tipo",
      kindOptions: { STRENGTH: "Ponto forte", DEVELOPMENT: "Ponto de desenvolvimento" },
      text: "Descrição",
      submit: "Registrar",
    },
    mentorships: {
      title: "Mapa de mentorias",
      direction: "Quem mentora quem, em qual competência e desde quando. Agrupado por mentor.",
      empty: "Nenhuma mentoria ativa.",
      since: "desde {date}",
      noCompetency: "geral",
      mentees: { one: "1 mentorado", other: "{count} mentorados" },
      add: "Nova mentoria",
      end: "Encerrar",
      endLabel: "Encerrar a mentoria com {name}",
      dialog: {
        title: "Nova mentoria",
        description: "Vínculo temporário entre duas pessoas do time, por competência. Não entra na timeline.",
        role: "Papel de {name}",
        roles: { mentor: "Mentora alguém", mentee: "Recebe mentoria" },
        mentee: "Pessoa mentorada",
        mentor: "Quem mentora",
        personPlaceholder: "Escolha a pessoa",
        competency: "Competência",
        general: "Geral",
        startedAt: "Início",
        note: "Observação",
        submit: "Registrar mentoria",
      },
      endDialog: {
        title: "Encerrar esta mentoria?",
        description: "{mentor} deixa de mentorar {mentee} ({competency}). O vínculo sai do mapa; o registro fica na auditoria.",
        confirm: "Encerrar mentoria",
      },
    },
    readiness: {
      title: "Prontidão para a próxima senioridade",
      direction:
        "Só aparece quem atende ao nível esperado em todas as competências da senioridade atual. Não é nota nem ordem: diz em quantas competências da próxima a pessoa já está no nível.",
      line: "atende ao nível esperado de {seniority} em {met} de {total} competências",
      empty: "Ninguém atende hoje a todas as competências da senioridade atual.",
      matrixEmpty: "A matriz de níveis esperados ainda não foi preenchida — sem ela não há prontidão.",
    },
    overview: {
      byStatus: "PDIs por status",
      stale: "PDIs parados",
      staleDirection: "Sem acompanhamento há mais de {days} dias. Um PDI sem acompanhamento é um PDI morto.",
      staleNone: "Nenhum PDI parado.",
      allPlans: "Todos os PDIs",
      columns: { member: "Pessoa", objective: "Objetivo", competency: "Competência", status: "Status", progress: "Ações", review: "Acompanhamento" },
      tableLabel: "PDIs do time",
    },
    validation: {
      mentorRequired: "Escolha quem é o mentor.",
      sameMentor: "Escolha duas pessoas diferentes.",
      duplicateMentorship: "Essa mentoria já está ativa.",
    },
    matrix: {
      tab: "Matriz de competências",
      direction: "Nível esperado (1 a 5) de cada competência por senioridade. Deixe em branco o que ainda não foi definido.",
      competency: "Competência",
      empty: "—",
      cellLabel: "Nível esperado de {competency} para {seniority}",
      none: "Não definido",
    },
  },
  dailies: {
    new: "Registrar daily",
    newTitle: "Daily de {date}",
    newSubtitle: "Revise os combinados, anote o que cada pessoa trouxe e registre os combinados de hoje.",
    date: "Data da daily",
    save: "Salvar daily",
    saveHint: "Ctrl+Enter salva tudo",
    forbidden: "Só quem escreve registra dailies.",
    otherDate: {
      label: "Data da daily",
      open: "Abrir",
      today: "Voltar para hoje",
      future: "A daily não pode ser no futuro.",
      retroactive:
        "Registro retroativo: combinados marcados como feitos ficam concluídos em {date}, e os prazos contam a partir desse dia.",
    },
    sameDay: {
      notice: {
        one: "Já existe uma daily registrada em {date}, salva às {time}.",
        other: "Já existem {count} dailies registradas em {date}; a primeira foi salva às {time}.",
      },
      open: "Abrir a daily registrada",
      hint: "Registrar outra continua possível.",
    },
    edit: {
      button: "Editar",
      title: "Editar daily",
      description: "Resumo, decisões, presença e notas. As linhas da timeline de cada pessoa acompanham a edição.",
      notEditable:
        "Revisões e combinados criados não se editam aqui: eles já mudaram os combinados. Corrija pelo próprio combinado.",
      shortcut: "Ctrl+Enter salva",
      submit: "Salvar alterações",
    },
    review: {
      title: "Revisão dos combinados",
      direction: "Criados na daily anterior e em aberto com prazo até o dia da daily.",
      emptyTitle: "Nada para revisar",
      emptyDirection: "A daily anterior não gerou combinados e nenhum combinado em aberto vence até o dia da daily.",
      outcomes: "Desfecho",
      done: "Feito",
      partial: "Parcial",
      notDone: "Não feito",
      keyHint: "F feito · P parcial · N não feito · setas trocam",
      undo: "Desfazer",
      blocker: "Impeditivo",
      blockerPlaceholder: "O que impediu, em uma linha",
      reason: "Motivo",
      reasonNone: "Sem motivo",
      action: "O que fazer com o combinado",
      reschedule: "Reagendar",
      replace: "Substituir por novo combinado",
      newDueDate: "Novo prazo",
      replacementTitle: "Novo combinado",
      replacementDueDate: "Prazo",
      fromPreviousDaily: "da daily anterior",
      due: "prazo",
    },
    participants: {
      title: "Participantes e notas",
      direction: "Todos presentes por padrão. Tab passa de uma pessoa para a próxima.",
      keyHint: "Alt+A marca ausente · Alt+B marca a nota como bloqueio",
      present: "Presente",
      absent: "Ausente",
      notePlaceholder: "Nota de {name}",
      blocker: "Bloqueio",
      markBlocker: "Marcar como bloqueio",
      unmarkBlocker: "Desmarcar bloqueio",
      count: "{present} de {total} presentes",
    },
    newAgreements: {
      title: "Combinados de hoje",
      direction: "Enter acrescenta outra linha. A daily de amanhã revisa estes combinados.",
      member: "Responsável",
      memberPlaceholder: "Pessoa",
      agreementTitle: "Combinado",
      dueDate: "Prazo",
      add: "Adicionar linha",
      remove: "Remover linha",
    },
    extra: {
      toggle: "Resumo e decisões",
      summary: "Resumo geral",
      decisions: "Decisões",
    },
    draft: {
      restored: "Rascunho restaurado ({time}). O que estava preenchido voltou.",
      discard: "Descartar rascunho",
      saved: "Rascunho salvo às {time}",
    },
    validation: {
      blockerRequired: "Descreva o impeditivo.",
      futureDue: "O novo prazo precisa ser depois da daily.",
      notBeforeDaily: "O prazo não pode ser antes da daily.",
      replacementRequired: "Informe o novo combinado.",
      agreementClosed: "Um dos combinados revisados já foi encerrado em outra tela. Recarregue a página.",
      rowIncomplete: "Preencha responsável, combinado e prazo, ou deixe a linha vazia.",
    },
    whatsapp: {
      copy: "Copiar para WhatsApp",
      copied: "Copiado",
      failed: "Não foi possível copiar",
    },
    pdf: {
      download: "Baixar PDF",
      downloading: "Gerando…",
      failed: "Não foi possível gerar o PDF",
      title: "Daily do Suporte — {date}",
      author: "Registrada por {name}",
      present: { one: "1 presente", other: "{count} presentes" },
      absent: "Ausentes: {names}",
      noRecord: "Sem anotação nesta daily: {names}",
      privateWarning: "Documento gerencial: inclui observações privadas. Não compartilhe fora da gestão.",
      reviewed: "Combinados de ontem",
      note: "Nota",
      blocker: "Bloqueio:",
      created: "Combinados de hoje | {date}",
      blockerText: "Impeditivo: {text}",
      newDue: "Novo prazo: {date}",
      replacedBy: "Substituído por: {title} ({date})",
      due: "prazo {date}",
      watching: "em observação ({heat})",
      summary: "Resumo",
      decisions: "Decisões",
      watchTitle: "Em observação",
      watchSubtitle: "{count} · do fogo alto ao baixo, a mais esquecida primeiro.",
      watchCount: { one: "1 ativa", other: "{count} ativas" },
      watchEmpty: "Nenhuma observação ativa.",
      watchTeam: "Time",
      watchAbove: "aparece acima, em {name}",
      watchAboveDaily: "aparece acima",
      watchUnreviewed: "sem revisão há {days} dias",
      watchColdHigh: "fogo alto há {days} dias sem mudar de grau",
      footer: "Prontuário · gerado em {date}",
      page: "Página {page} de {total}",
    },
    history: {
      tableLabel: "Dailies registradas",
      count: { one: "1 daily", other: "{count} dailies" },
      present: "presentes",
      blockers: { one: "1 bloqueio", other: "{count} bloqueios" },
      reviewed: { one: "1 revisado", other: "{count} revisados" },
      created: { one: "1 criado", other: "{count} criados" },
      expand: "Ver detalhe",
      collapse: "Recolher",
      open: "Abrir daily",
      emptyTitle: "Nenhuma daily registrada",
      emptyDirection: "Ao registrar uma daily, os combinados da anterior e os vencidos entram para revisão automaticamente.",
    },
    detail: {
      reviewed: "Combinados revisados",
      created: "Combinados criados",
      notes: "Notas",
      absent: "Ausentes",
      summary: "Resumo geral",
      decisions: "Decisões",
      replacedBy: "substituído por",
      newDue: "novo prazo",
      author: "Registrada por {name}",
      none: "Nada registrado",
    },
  },
  forms: {
    date: "Data",
    datePlaceholder: "DD/MM/AAAA",
    visibility: "Visibilidade",
    visibilityHelp: {
      PRIVATE: "Só você vê.",
      SHARED: "Quem tem acesso de leitura também vê.",
    },
    saveChanges: "Salvar alterações",
    editDescription: "{name}. A timeline acompanha a alteração.",
    edit: "Editar",
    delete: "Excluir",
    deleteDialog: {
      title: "Excluir este registro?",
      description:
        "{type} de {name}, de {date}. Sai da timeline e das listas. Os combinados gerados nele continuam. A exclusão fica registrada na auditoria.",
      confirm: "Excluir registro",
    },
    oneOnOne: {
      title: "Registrar 1:1",
      editTitle: "Editar 1:1",
      description: "Com {name}. Nasce privado.",
      topics: "Assuntos tratados",
      duration: "Duração (min)",
      perceptions: "Percepções",
      memberPerception: "Percepção do colaborador",
      managerPerception: "Percepção do gestor",
      progress: "Conquistas e dificuldades",
      wins: "Conquistas",
      difficulties: "Dificuldades",
      next: "Desenvolvimento e próxima revisão",
      development: "Desenvolvimento",
      nextReviewAt: "Próxima revisão",
      submit: "Registrar 1:1",
    },
    feedback: {
      title: "Dar feedback",
      editTitle: "Editar feedback",
      description: "Para {name}. Contexto, comportamento e impacto, nessa ordem.",
      category: "Categoria",
      context: "Contexto",
      contextHelp: "Quando e onde aconteceu.",
      behavior: "Comportamento observado",
      behaviorHelp: "O que a pessoa fez, específico e sem interpretação.",
      impact: "Impacto",
      impactHelp: "O efeito no cliente, no time ou no resultado.",
      guidance: "Orientação",
      guidanceHelp: "O que fica combinado daqui pra frente.",
      followUpAt: "Follow-up",
      recognitionHint: "Reconhecimento sugere compartilhar. Você pode manter privado.",
      suggestion: "Contexto sugerido",
      useSuggestion: "Usar como contexto",
      submit: "Registrar feedback",
    },
    generated: {
      title: "Combinados gerados",
      direction: "O que ficou combinado com {name}, com prazo. Entra na lista de combinados e na próxima daily.",
      agreementTitle: "O que foi combinado",
      dueDate: "Prazo",
      add: "Adicionar combinado",
      remove: "Remover combinado",
      count: { one: "1 combinado", other: "{count} combinados" },
    },
    context: {
      title: "Contexto",
      show: "Mostrar contexto",
      hide: "Ocultar contexto",
      direction: "Somente leitura. O que ficou do encontro anterior e o que está em aberto.",
      loading: "Carregando o contexto",
      failed: "Não foi possível carregar o contexto.",
      previous: "Do 1:1 anterior",
      previousDate: "Do 1:1 de {date}",
      previousNone: "Nenhum 1:1 anterior registrado.",
      nextReview: "Revisão marcada",
      development: "Desenvolvimento",
      difficulties: "Dificuldades",
      topics: "Assuntos",
      generated: "Combinados gerados nele",
      openAgreements: "Combinados em aberto",
      openAgreementsNone: "Nenhum combinado em aberto.",
      lastFeedback: "Último feedback",
      lastFeedbackNone: "Nenhum feedback registrado.",
      guidance: "Orientação",
      followUp: "Follow-up",
      plans: "PDI ativo",
      plansNone: "Nenhum PDI ativo.",
      lastReview: "Último acompanhamento",
      neverReviewed: "nunca acompanhado",
      openActions: "Ações em aberto",
    },
    note: {
      title: "Anotação",
      editTitle: "Editar anotação",
      description: "Sobre {name}. Nasce privada.",
      noteTitle: "Título",
      body: "Anotação",
      submit: "Salvar anotação",
    },
    agreement: {
      title: "Novo combinado",
      description: "Com {name}. Só o que foi combinado e o prazo são obrigatórios.",
      agreementTitle: "O que foi combinado",
      member: "Responsável",
      memberPlaceholder: "Selecione a pessoa",
      descriptionGeneral: "Só o que foi combinado, o responsável e o prazo são obrigatórios.",
      dueDate: "Prazo",
      details: "Detalhes",
      priority: "Prioridade",
      origin: "Origem",
      shortcut: "Enter salva · Ctrl+Enter salva e abre outro",
      submit: "Criar combinado",
      savedAnother: "Combinado criado. Pode lançar o próximo.",
    },
  },
  priorityValidations: {
    title: "Validação de prioridade",
    subtitle: {
      today: "Hoje, {date}",
      range: "De {from} a {to}",
    },
    form: {
      label: "Registrar validação de prioridade",
      ticketUrl: "URL do chamado",
      ticketUrlPlaceholder: "Cole a URL do chamado",
      ticketRef: "ID do chamado",
      ticketRefPlaceholder: "ID",
      recognized: "ID extraído pelo padrão {pattern}",
      notRecognized: "Nenhum padrão reconheceu. Digite o ID.",
      member: "Responsável",
      memberPlaceholder: "Pessoa",
      analystPriority: "Prioridade do analista",
      supervisorPriority: "Prioridade validada",
      priorityPlaceholder: "Prioridade",
      returned: "Devolver para reanálise",
      outcome: "Resultado",
      outcomePending: "Aguardando prioridades",
      reason: "Motivo da alteração",
      reasonPlaceholder: "Motivo",
      reasonOther: "Qual motivo",
      reasonOtherPlaceholder: "Descreva o motivo",
      note: "Observação",
      notePlaceholder: "Opcional, uma linha",
      submit: "Registrar",
      shortcut: "Ctrl+Enter registra e volta para a URL",
      saved: "Chamado {ref} registrado.",
      editing: "Editando a validação do chamado {ref}.",
      cancelEdit: "Cancelar edição",
      saveEdit: "Salvar alteração",
      updated: "Validação do chamado {ref} atualizada.",
      noLevels: "Cadastre os níveis de prioridade em Configurações antes de validar chamados.",
    },
    summary: {
      label: "Resumo do período",
      evaluated: "Avaliados",
      maintained: "Mantidos",
      changed: "Alterados",
      raised: "Elevados",
      lowered: "Rebaixados",
      returned: "Devolvidos",
      changeRate: "{rate}% de {total}",
    },
    empty: {
      todayTitle: "Nenhum chamado validado hoje",
      todayDirection: "Cole a URL do primeiro chamado no formulário acima. O resumo do dia aparece a partir do primeiro registro.",
      todayDirectionReadOnly: "As validações registradas hoje aparecem aqui, com o resumo do dia.",
      periodTitle: "Nenhuma validação no período",
      filteredTitle: "Nenhuma validação com estes filtros",
      periodDirection: "Escolha outro período na barra de cima.",
      filteredDirection: "Ajuste ou limpe os filtros para ver mais validações.",
    },
    table: {
      label: "Validações de prioridade",
      date: "Data",
      time: "Hora",
      ticket: "Chamado",
      member: "Responsável",
      analyst: "Analista",
      supervisor: "Validada",
      outcome: "Resultado",
      reason: "Motivo",
      actions: "Ações",
      openTicket: "Abrir o chamado {ref} em nova aba",
      rowActions: "Ações da validação do chamado {ref}",
      edit: "Editar",
      delete: "Excluir",
      none: "—",
    },
    deleteDialog: {
      title: "Excluir validação",
      description: "A validação do chamado {ref} sai da tabela e dos resumos. O registro fica guardado na auditoria.",
      confirm: "Excluir validação",
      keep: "Manter validação",
    },
    filters: {
      button: "Filtros",
      periods: { today: "Hoje", "7d": "7 dias", "30d": "30 dias", month: "Mês atual", custom: "Personalizado" },
      member: "Responsável",
      allMembers: "Todos",
      outcome: "Resultado",
      allOutcomes: "Todos",
      reason: "Motivo",
      allReasons: "Todos",
      clear: "Limpar filtros",
    },
    validation: {
      ticketRefRequired: "Informe o ID do chamado.",
      reasonRequired: "Escolha o motivo da alteração.",
      reasonOtherRequired: "Descreva o motivo.",
    },
    profile: {
      title: "Validação de prioridade",
      window: "últimos {days} dias",
      total: "Validações",
      changeRate: "Taxa de alteração",
      changeRateValue: "{rate}% · {changed} de {total}",
      topReason: "Motivo mais frequente",
      topReasonValue: "{label} ({count})",
      none: "Nenhuma validação nos últimos {days} dias.",
      noReason: "Nenhuma alteração",
      seeAll: "Ver validações",
      feedback: "Registrar feedback sobre isto",
      suggestion:
        "Validação de prioridade nos últimos {days} dias: {changed} de {total} chamados tiveram a prioridade alterada. Motivo mais frequente: {reason}.",
    },
  },
  /** P21 — Em observação (D24–D27). */
  watch: {
    title: "Em observação",
    subtitle: "O que você acompanha de perto, do fogo alto ao baixo. O mais esquecido de cada grau fica no topo.",
    heat: { HIGH: "Fogo alto", MEDIUM: "Fogo médio", LOW: "Fogo baixo" },
    origin: {
      DAILY: "Daily",
      AGREEMENT: "Combinado",
      PRIORITY_VALIDATION: "Validação",
      DEV_RETURN: "Devolução",
      ONE_ON_ONE: "1:1",
      FEEDBACK: "Feedback",
      MANUAL: "Manual",
    },
    actions: {
      watch: "Colocar em observação",
      new: "Nova observação",
      reviewed: "Revisado hoje",
      cool: "Esfriar",
      heat: "Esquentar",
      resolve: "Resolver",
      archive: "Arquivar",
      open: "Abrir observação",
      reopenExisting: "Em observação: abrir",
      share: "Compartilhar com a leitura",
      unshare: "Tornar privada",
      rowActions: "Ações da observação {title}",
    },
    button: {
      label: "Colocar em observação",
      watching: "Em observação ({heat}) — abrir",
      title: "Título",
      heat: "Grau",
      context: "Contexto",
      contextPlaceholder: "Opcional: o que observar",
      save: "Colocar em observação",
      cancel: "Cancelar",
      saved: "Em observação.",
      pending: "Fica ligada a esta daily quando você salvar.",
      pendingRecord: "Fica ligada ao registro quando você salvar.",
    },
    tabs: {
      label: "Situação das observações",
      active: "Ativas",
      unreviewed: "Sem revisão",
      resolved: "Resolvidas",
      archived: "Arquivadas",
      all: "Todas",
    },
    filters: {
      button: "Filtros",
      heat: "Grau",
      allHeats: "Todos",
      member: "Pessoa",
      allMembers: "Todas",
      origin: "Origem",
      allOrigins: "Todas",
      clear: "Limpar filtros",
    },
    group: { one: "{heat} · 1", other: "{heat} · {count}" },
    review: {
      ok: "em dia",
      due: "sem revisão",
      late: "muito atrasada",
      daysSince: { one: "1 dia", other: "{count} dias" },
      today: "hoje",
      count: { one: "1 revisão", other: "{count} revisões" },
      none: "nunca revisada",
    },
    coldHigh: "fogo alto há {days} dias sem mudar de grau",
    resolved: "Resolvida em {date}",
    archived: "Arquivada em {date}",
    resolveForm: {
      title: "Resolver observação",
      note: "Resolução",
      placeholder: "O que aconteceu? O que você aprendeu?",
      required: "Escreva a resolução: é o que fica registrado.",
      confirm: "Resolver",
      cancel: "Cancelar",
      done: "Observação resolvida.",
    },
    reviewedToast: "Revisada hoje.",
    heatToast: "Agora em {heat}.",
    archivedToast: "Observação arquivada.",
    empty: {
      active: "Nada em observação",
      activeDirection: "Coloque em observação a partir da daily, de um combinado, de uma validação, de uma devolução, de um 1:1 ou com \u201cNova observação\u201d.",
      unreviewed: "Nada sem revisão",
      unreviewedDirection: "Todas as observações ativas estão em dia com a cadência do grau.",
      resolved: "Nenhuma observação resolvida",
      archived: "Nenhuma observação arquivada",
      filtered: "Nenhuma observação com estes filtros",
      filteredDirection: "Ajuste ou limpe os filtros.",
    },
    detail: {
      context: "Contexto",
      link: "Vínculo",
      created: "Criada em {date}",
      history: "Histórico de revisões",
      historyEmpty: "Ainda não revisada.",
      heatChange: "{before} → {after}",
      reviewed: "revisada",
      resolution: "Resolução",
      visibility: "Visibilidade",
      neverWhatsApp: "Observações nunca entram no texto da daily para WhatsApp.",
    },
    links: {
      member: "Pessoa",
      central: "Central",
      agreement: "Combinado",
      daily: "Daily de {date}",
      validation: "Validação {ref}",
      devReturn: "Devolução {ref}",
      oneOnOne: "1:1 de {date}",
      feedback: "Feedback de {date}",
    },
    profile: {
      title: "Em observação",
      empty: "Nada em observação para {name}.",
      more: { one: "e mais 1", other: "e mais {count}" },
      seeAll: "Ver em observação",
    },
    timeline: {
      created: "Em observação ({heat}): {title}",
      resolved: "Observação resolvida: {title}",
      createdSummary: "Colocado em observação em {date}.",
      resolvedSummary: "Colocado em observação em {created}, resolvido em {resolved}: {note}",
    },
    validation: {
      title: "Dê um título à observação.",
    },
  },
  /** P20 — Devolução do desenvolvimento (D21, D22). */
  devReturns: {
    title: "Devoluções do desenvolvimento",
    tabs: {
      label: "Qualidade da triagem",
      validations: "Validações de prioridade",
      devReturns: "Devoluções do desenvolvimento",
    },
    subtitle: {
      today: "Hoje, {date}",
      range: "De {from} a {to}",
    },
    form: {
      label: "Registrar devolução do desenvolvimento",
      ticketUrl: "URL do chamado",
      ticketUrlPlaceholder: "Cole a URL do chamado",
      ticketRef: "ID do chamado",
      member: "Analista",
      memberPlaceholder: "Pessoa",
      returnedAt: "Data da devolução",
      reason: "Motivo",
      reasonPlaceholder: "Motivo",
      reasonOther: "Qual motivo",
      reasonOtherPlaceholder: "Descreva o motivo",
      devContact: "Quem devolveu",
      devContactPlaceholder: "Nome ou time",
      note: "Observação",
      notePlaceholder: "Opcional, uma linha",
      submit: "Registrar",
      shortcut: "Ctrl+Enter registra e volta para a URL",
      saved: "Devolução do chamado {ref} registrada.",
      editing: "Editando a devolução do chamado {ref}.",
      cancelEdit: "Cancelar edição",
      saveEdit: "Salvar alteração",
      updated: "Devolução do chamado {ref} atualizada.",
      validationContext: "Validado em {date} — prioridade do analista {analyst}, validada {supervisor}, resultado {outcome}",
      validationContextReturned: "Validado em {date} — prioridade do analista {analyst}, devolvido para reanálise",
      validationMore: "(a mais recente de {count} validações deste chamado)",
      noValidation: "Sem validação de prioridade para este chamado.",
      previousReturns: { one: "Este chamado já foi devolvido 1 vez.", other: "Este chamado já foi devolvido {count} vezes." },
      noReasons: "Cadastre os motivos de devolução em Configurações antes de registrar.",
    },
    summary: {
      label: "Resumo do período",
      total: "Devoluções",
      attributable: "Atribuíveis ao analista",
      process: "De processo",
      resolved: "Reenviadas",
      open: "Em aberto",
      rate: "{rate} ({count} de {total} chamados)",
      countOnly: "{count} · sem chamado validado no período",
      lowConfidence: "amostra pequena",
      lowConfidenceHelp: "Menos de {min} chamados validados no período: a taxa oscila muito com poucos casos.",
      avgDays: { one: "1 dia até o reenvio, em média", other: "{count} dias até o reenvio, em média" },
    },
    empty: {
      todayTitle: "Nenhuma devolução registrada hoje",
      todayDirection: "Cole a URL do chamado devolvido no formulário acima.",
      todayDirectionReadOnly: "As devoluções registradas aparecem aqui, com o resumo do período.",
      periodTitle: "Nenhuma devolução no período",
      filteredTitle: "Nenhuma devolução com estes filtros",
      periodDirection: "Escolha outro período na barra de cima.",
      filteredDirection: "Ajuste ou limpe os filtros para ver mais devoluções.",
    },
    table: {
      label: "Devoluções do desenvolvimento",
      date: "Data",
      ticket: "Chamado",
      member: "Analista",
      central: "Central",
      reason: "Motivo",
      devContact: "Quem devolveu",
      resolved: "Reenviado",
      actions: "Ações",
      openTicket: "Abrir o chamado {ref} em nova aba",
      rowActions: "Ações da devolução do chamado {ref}",
      resolve: "Marcar como reenviado",
      edit: "Editar",
      delete: "Excluir",
      notResolved: "em aberto",
      none: "—",
      validated: "validado",
      validatedTitle: "Chamado com validação de prioridade: {outcome}",
    },
    resolveDialog: {
      title: "Marcar como reenviado",
      description: "O chamado {ref} voltou corrigido para o desenvolvimento. A resolução é opcional.",
      date: "Data do reenvio",
      note: "Resolução",
      notePlaceholder: "Opcional: o que foi corrigido",
      confirm: "Marcar como reenviado",
      cancel: "Cancelar",
      done: "Chamado {ref} marcado como reenviado.",
    },
    deleteDialog: {
      title: "Excluir devolução",
      description: "A devolução do chamado {ref} sai da tabela e dos resumos. O registro fica guardado na auditoria.",
      confirm: "Excluir devolução",
      keep: "Manter devolução",
    },
    filters: {
      button: "Filtros",
      member: "Analista",
      allMembers: "Todos",
      reason: "Motivo",
      allReasons: "Todos",
      category: "Categoria",
      allCategories: "Todas",
      openOnly: "Apenas em aberto",
      clear: "Limpar filtros",
    },
    validation: {
      ticketRefRequired: "Informe o ID do chamado.",
      reasonRequired: "Escolha o motivo da devolução.",
      reasonOtherRequired: "Descreva o motivo.",
      futureDate: "A data não pode ser no futuro.",
      resolvedBeforeReturn: "O reenvio não pode ser antes da devolução.",
    },
    profile: {
      title: "Devoluções do desenvolvimento",
      window: "últimos {days} dias",
      total: "Devoluções",
      totalValue: "{count} de {total} chamados validados",
      totalValueNoValidations: "{count} · nenhum chamado validado",
      attributable: "Atribuíveis ao analista",
      attributableValue: "{count} de {total}",
      topReason: "Motivo mais frequente",
      topReasonValue: "{label} ({count})",
      series: "Últimos 6 meses",
      seriesLabel: "Devoluções por mês nos últimos 6 meses: {values}",
      none: "Nenhuma devolução nos últimos {days} dias.",
      seeAll: "Ver devoluções",
      feedback: "Registrar feedback sobre isto",
      suggestion:
        "Devoluções do desenvolvimento nos últimos {days} dias: {count} de {total} chamados validados, {attributable} atribuíveis ao analista. Motivo mais frequente: {reason}.",
    },
    overlap: {
      title: "Prioridade alterada e devolvido",
      direction:
        "Chamados que tiveram a prioridade alterada na validação e também voltaram do desenvolvimento: costuma ser um problema de triagem, não dois problemas separados.",
      count: { one: "1 chamado no período", other: "{count} chamados no período" },
      empty: "Nenhum chamado com prioridade alterada e devolução no período.",
      returns: { one: "1 devolução", other: "{count} devoluções" },
    },
  },
  /** P19 — Central de atendimento (D20). */
  centrals: {
    field: "Central",
    placeholder: "Opcional",
    searchLabel: "Central de atendimento",
    noneActive: "Nenhuma central cadastrada. Digite para criar.",
    create: "Criar central: {name}",
    creating: "Criando…",
    usingExisting: "usando a central já cadastrada: {name}",
    notSaved: "Central não gravada: escolha uma da lista ou “Criar central”.",
    inactive: "A central {name} está desativada. Reative em Configurações → Centrais.",
    clear: "Limpar central",
    none: "Sem central informada",
    column: "Central",
    filter: "Central",
    filterAll: "Todas as centrais",
    filterNone: "Sem central informada",
    settings: {
      direction:
        "Lista das centrais de atendimento. O nome é normalizado: “Central Alfa” e “central alfa” são a mesma central. Desativar tira dos formulários sem apagar o histórico.",
      new: "Nova central",
      dialogTitle: { create: "Nova central", edit: "Editar central" },
      dialogDescription: "O nome aparece nos combinados, nas validações e no texto da daily.",
      label: "Nome",
      labelPlaceholder: "Ex.: Central Alfa",
      note: "Observação",
      externalId: "ID na plataforma",
      noExternalId: "—",
      emptyTitle: "Nenhuma central",
      emptyDirection: "Cadastre aqui, importe uma lista abaixo ou crie direto no formulário, digitando o nome.",
      duplicate: "Já existe a central {name} (mesmo nome normalizado).",
    },
    import: {
      title: "Importar lista",
      direction:
        "Cole uma central por linha. Aceita uma coluna (CSV simples) ou “nome;ID na plataforma”. Nada é sobrescrito nem reativado: o que já existe é ignorado.",
      textarea: "Lista de centrais",
      placeholder: "Central Alfa\nCentral Beta;CB-002",
      preview: "Pré-visualizar",
      confirm: "Importar {count}",
      cancel: "Descartar",
      summary: "{created} · {existing} · {invalid}",
      created: { one: "1 nova", other: "{count} novas" },
      existing: { one: "1 já existe (ignorada)", other: "{count} já existem (ignoradas)" },
      invalid: { one: "1 linha vazia ou inválida", other: "{count} linhas vazias ou inválidas" },
      newList: "Serão criadas",
      existingList: "Ignoradas",
      existingAs: "já existe como {name}",
      existingInactive: "já existe como {name} (desativada — não será reativada)",
      invalidList: "Não importadas",
      line: "linha {line}",
      reasons: {
        noName: "sem nome",
        tooLong: "nome ou ID longo demais",
        tooManyFields: "mais de um “;”",
        header: "cabeçalho",
      },
      nothing: "Nenhuma central nova para importar.",
      done: { one: "1 central importada", other: "{count} centrais importadas" },
      tooLarge: "Cole no máximo 2.000 linhas por vez.",
    },
    metrics: {
      title: "Por central",
      direction:
        "Volume por central no período: combinados criados, chamados validados, quanto a prioridade foi alterada e em quantas dailies a central apareceu. A unidade é a central, não a pessoa.",
      columns: {
        central: "Central",
        agreements: "Combinados",
        validations: "Validações",
        dispute: "Alteração de prioridade",
        dailies: "Dailies",
      },
      disputeRate: "{rate} · {changed} de {total}",
      noValidations: "sem validação",
      dailiesCount: { one: "1 daily", other: "{count} dailies" },
      inactive: "desativada",
      empty: "Nenhum combinado ou validação no período",
      emptyDirection: "A seção se preenche quando combinados e validações começam a registrar a central.",
      coverage: "Central informada em {agreements} dos combinados e {validations} das validações do período.",
      coverageRate: "{rate} ({count} de {total})",
    },
  },
  settings: {
    title: "Configurações",
    tabsLabel: "Seções das configurações",
    tabs: {
      priorityLevels: "Níveis de prioridade",
      reclassificationReasons: "Motivos de reclassificação",
      blockerReasons: "Motivos de impeditivo",
      ticketPatterns: "Padrões de URL",
      competencies: "Competências",
      competencyMatrix: "Matriz de competências",
      thresholds: "Limiares de alerta",
      metrics: "Métricas",
      score: "Score",
      centrals: "Centrais",
      devReturnReasons: "Motivos de devolução",
    },
    metrics: {
      direction:
        "Cadastro das métricas operacionais que um dia virão do helpdesk. Nenhum resultado é importado nem exibido no MVP: métrica é insumo de conversa, não avaliação.",
      new: "Nova métrica",
      dialogTitle: { create: "Nova métrica", edit: "Editar métrica" },
      dialogDescription: "A chave casa a importação futura e não muda depois de criada.",
      label: "Rótulo",
      labelPlaceholder: "Ex.: SLA de primeira resposta",
      key: "Chave",
      keyPlaceholder: "Ex.: sla_first_response",
      keyHelp: "Minúsculas, números e _. Não muda depois de criada.",
      keyLocked: "A chave não muda depois de criada.",
      unit: "Unidade",
      unitPlaceholder: "Ex.: %, min, chamados",
      directionField: "Direção",
      sourceSystem: "Sistema de origem",
      sourceSystemPlaceholder: "Ex.: helpdesk",
      results: "Resultados",
      noResults: "nenhum",
      emptyTitle: "Nenhuma métrica cadastrada",
      emptyDirection: "Cadastre as métricas antes de montar uma definição de score.",
      invalidKey: "Use minúsculas, números e _ (de 2 a 40), começando por letra.",
      duplicateKey: "Já existe uma métrica com essa chave.",
    },
    score: {
      title: "Definições de score",
      direction:
        "Arquitetura apenas: nenhum score é calculado nem exibido no MVP. Aqui fica a composição — quais métricas entrariam, com que peso e em que faixa. Mudar uma versão ativa exige versão nova, para nunca reescrever o passado.",
      new: "Nova definição",
      tableLabel: "Definições de score e versões",
      columns: { name: "Definição", version: "Versão", status: "Status", components: "Métricas", weights: "Soma dos pesos", created: "Criada em" },
      versionLabel: "v{version}",
      active: "Ativa",
      draft: "Rascunho",
      locked: "Travada",
      weightOk: "100%",
      weightMissing: "{sum}% · faltam {missing}",
      weightOver: "{sum}% · passa {over}",
      emptyTitle: "Nenhuma definição de score",
      emptyDirection: "Crie uma definição para documentar como um score seria composto. Nada é calculado.",
      createDialog: {
        title: "Nova definição de score",
        description: "Nasce como versão 1, em rascunho e sem métricas.",
        name: "Nome",
        namePlaceholder: "Ex.: Qualidade do atendimento",
        notes: "Notas",
        notesHelp: "Para que serve e o que não deve virar (ex.: não é ranking).",
        submit: "Criar definição",
      },
      detail: {
        back: "Definições de score",
        notes: "Notas",
        notesEmpty: "Sem notas.",
        saveNotes: "Salvar notas",
        components: "Composição",
        componentsEmpty: "Nenhuma métrica nesta versão.",
        metric: "Métrica",
        direction: "Direção",
        weight: "Peso (%)",
        min: "Faixa: mínimo",
        max: "Faixa: máximo",
        range: "Faixa de normalização",
        rangeText: "de {min} a {max}",
        add: "Incluir métrica",
        addTitle: "Incluir métrica",
        editTitle: "Editar {metric}",
        addDescription: "Peso em pontos percentuais. A faixa diz que valores da métrica seriam o pior e o melhor caso — nada é calculado.",
        save: "Salvar componente",
        remove: "Tirar",
        removeLabel: "Tirar {metric} da composição",
        edit: "Editar",
        sum: "Soma dos pesos",
        sumHelp: "Precisa fechar 100% para a versão poder ser ativada.",
        lockedHelp: "Versão ativa (ou com resultado) não muda: crie uma versão nova para alterar a composição.",
        activate: "Ativar versão",
        deactivate: "Desativar",
        newVersion: "Nova versão",
        preview: "Pré-visualizar",
        delete: "Excluir rascunho",
        versions: "Versões",
        inactiveMetric: "métrica desativada",
        activateDialog: {
          title: "Ativar a versão {version}?",
          description: "Fica sendo a versão de “{name}”; outra versão ativa com esse nome é desativada. Nada é calculado: ativar só congela a composição.",
          confirm: "Ativar versão",
        },
        deleteDialog: {
          title: "Excluir este rascunho?",
          description: "“{name}” v{version} e a composição dele saem do cadastro. A exclusão fica na auditoria.",
          confirm: "Excluir rascunho",
        },
      },
      preview: {
        title: "Pré-visualização",
        subtitle: "{name} · v{version}",
        direction:
          "Documentação viva da fórmula, não execução dela. Mostra quais métricas entrariam, com que peso e em que direção. Nenhum valor de pessoa é lido.",
        composition: "Composição dos pesos (%)",
        compositionLabel: "Pesos: {parts}",
        how: "Como seria lido",
        howLines: [
          "Cada métrica seria levada para uma escala comum dentro da faixa de normalização: o mínimo é o pior caso e o máximo, o melhor — invertido quando menor é melhor.",
          "Cada métrica entraria com o seu peso; os pesos somam 100%.",
          "Todo número exibido viria com as parcelas que o formaram e a cobertura (quantos chamados ou avaliações) de cada métrica. Sem parcelas, nada é exibido.",
        ],
        notCalculated: "Nenhum score é calculado no MVP. Esta tela não lê resultado de ninguém.",
        incomplete: "A soma dos pesos está em {sum}%: a composição ainda não fecha.",
        empty: "Esta versão não tem métricas.",
        edit: "Voltar à definição",
      },
      validation: {
        nameRequired: "Dê um nome à definição.",
        duplicateName: "Já existe uma definição com esse nome. Crie uma versão nova dela.",
        metricRequired: "Escolha a métrica.",
        weight: "Peso entre 0,1 e 100.",
        number: "Informe um número.",
        range: "O máximo precisa ser maior que o mínimo.",
        locked: "Versão ativa ou com resultado não muda. Crie uma versão nova.",
        inactiveMetric: "Métrica desativada não entra em composição nova.",
        noComponents: "Inclua ao menos uma métrica antes de ativar.",
        weightSum: "Os pesos precisam somar 100% para ativar.",
      },
    },
    thresholds: {
      direction:
        "Quando cada alerta da tela Hoje dispara. Os alertas não são gravados: mudar um limiar muda a lista, os contadores, a coluna de atenção da equipe e o perfil na hora.",
      tableLabel: "Limiares do motor de alertas",
      columns: { alert: "Alerta", value: "Valor", default: "Padrão" },
      defaultValue: "padrão {value}",
      reset: "Voltar ao padrão",
      resetLabel: "Voltar {name} ao padrão ({value})",
      custom: "alterado",
      outOfRange: "Use um valor entre {min} e {max}.",
      saved: "Limiar salvo",
      oneOnOne: "Sem 1:1 — {seniority}",
      oneOnOneHelp: "Dias sem 1:1 acima dos quais a pessoa aparece. Acima de 1,5x vira laranja; acima do dobro, vermelho.",
      items: {
        dueSoonDays: { name: "Combinado vencendo", help: "Dias até o prazo.", unit: "dias" },
        watchHighCadenceDays: { name: "Em observação — fogo alto", help: "Revisar a cada N dias.", unit: "dias" },
        watchMediumCadenceDays: { name: "Em observação — fogo médio", help: "Revisar a cada N dias.", unit: "dias" },
        watchLowCadenceDays: { name: "Em observação — fogo baixo", help: "Revisar a cada N dias.", unit: "dias" },
        watchStaleHighDays: {
          name: "Fogo alto frio",
          help: "Dias em fogo alto sem mudar de grau: ou não era fogo alto, ou o assunto está travado.",
          unit: "dias",
        },
        chronicReschedules: {
          name: "Combinado crônico",
          help: "Reagendamentos, com o combinado ainda em aberto. Também muda o selo vermelho \u201carrastado Nx\u201d.",
          unit: "vezes",
        },
        defaultOneOnOneDays: { name: "Sem 1:1 — outras senioridades", help: "Para senioridade sem valor próprio.", unit: "dias" },
        silenceDays: { name: "Silêncio gerencial", help: "Dias sem nenhum registro de qualquer tipo sobre a pessoa.", unit: "dias" },
        stalePlanDays: { name: "PDI parado", help: "Dias de PDI ativo sem acompanhamento.", unit: "dias" },
        dailyMissingDays: { name: "Daily não registrada", help: "Dias úteis seguidos sem daily (hoje não conta).", unit: "dias úteis" },
        adherenceDropPoints: {
          name: "Cumprimento em queda — queda",
          help: "Pontos percentuais de queda entre os últimos 30 dias e os 30 anteriores.",
          unit: "p.p.",
        },
        adherenceMinSample: {
          name: "Cumprimento em queda — amostra",
          help: "Combinados devidos em cada janela para a queda valer.",
          unit: "combinados",
        },
      },
      days: "dias",
    },
    readOnly: "Somente leitura: só o gestor altera as configurações.",
    columns: {
      order: "Ordem",
      label: "Nome",
      status: "Status",
      usage: "Em uso",
      actions: "Ações",
      key: "Chave",
      rank: "Rank",
      category: "Categoria",
      requiresDetail: "Exige texto",
      regex: "Expressão",
      captureGroup: "Grupo",
    },
    active: "Ativo",
    inactive: "Inativo",
    yes: "Sim",
    no: "Não",
    usage: { one: "1 registro", other: "{count} registros" },
    unused: "Sem uso",
    moveUp: "Subir {label}",
    moveDown: "Descer {label}",
    edit: "Editar",
    activate: "Ativar",
    deactivate: "Desativar",
    delete: "Excluir",
    rowActions: "Ações de {label}",
    inUse: "Em uso por {count} registros. Desative em vez de excluir: o histórico continua apontando para ele.",
    deleteDialog: {
      title: "Excluir {label}",
      description: "O item some das configurações e das listas de escolha. Não há registros usando este item.",
      confirm: "Excluir",
      keep: "Manter",
    },
    priorityLevels: {
      direction:
        "Do mais alto para o mais baixo. A ordem define se uma validação foi elevada ou rebaixada. Reordenar não muda validações já registradas: cada uma guarda os ranks do momento.",
      new: "Novo nível",
      dialogTitle: { create: "Novo nível de prioridade", edit: "Editar nível de prioridade" },
      dialogDescription: "Entra no fim da lista; ajuste a posição com Subir e Descer.",
      label: "Nome",
      labelPlaceholder: "Ex.: Urgente",
      emptyTitle: "Nenhum nível de prioridade",
      emptyDirection: "Cadastre os níveis usados no helpdesk, do mais alto para o mais baixo.",
    },
    devReturnReasons: {
      direction:
        "Aparecem no formulário de devolução do desenvolvimento, agrupados por categoria e nesta ordem. A categoria separa o que é treinável no analista do que é atrito entre as áreas (D22).",
      new: "Novo motivo",
      dialogTitle: { create: "Novo motivo de devolução", edit: "Editar motivo de devolução" },
      dialogDescription: "Processo é para quando a devolução não é falha do analista.",
      label: "Motivo",
      labelPlaceholder: "Ex.: Falta de informação no chamado",
      category: "Categoria",
      requiresDetail: "Exige descrever o motivo",
      requiresDetailHelp: "Ao escolher este motivo, é preciso escrever qual é.",
      emptyTitle: "Nenhum motivo de devolução",
      emptyDirection: "Sem motivos não é possível registrar devolução do desenvolvimento.",
    },
    reclassificationReasons: {
      direction: "Aparecem no formulário de validação quando o resultado não é Mantida, nesta ordem.",
      new: "Novo motivo",
      dialogTitle: { create: "Novo motivo de reclassificação", edit: "Editar motivo de reclassificação" },
      dialogDescription: "Motivo genérico, como Outro, pode exigir que o texto seja descrito.",
      label: "Motivo",
      labelPlaceholder: "Ex.: Impacto superestimado",
      requiresDetail: "Exige descrever o motivo",
      requiresDetailHelp: "Ao escolher este motivo, o supervisor precisa escrever qual é.",
      emptyTitle: "Nenhum motivo de reclassificação",
      emptyDirection: "Sem motivos não é possível registrar validação elevada, rebaixada ou devolvida.",
    },
    competencies: {
      direction:
        "Base dos níveis avaliados no cadastro, dos PDIs e da matriz de níveis esperados. Em ordem de categoria e nome. Desativar tira a competência das telas sem apagar o histórico.",
      new: "Nova competência",
      dialogTitle: { create: "Nova competência", edit: "Editar competência" },
      dialogDescription: "O nome aparece no perfil, no PDI e na matriz.",
      label: "Nome",
      labelPlaceholder: "Ex.: Análise de log",
      category: "Categoria",
      categoryPlaceholder: "Ex.: Técnica",
      description: "Descrição",
      emptyTitle: "Nenhuma competência",
      emptyDirection: "Sem competências, o perfil não mostra níveis e a matriz fica vazia.",
      noCategory: "Sem categoria",
    },
    blockerReasons: {
      direction:
        "Aparecem na revisão da daily, nesta ordem. A categoria separa cumprimento bruto de ajustado: externo e capacidade não pesam como interno.",
      new: "Novo motivo",
      dialogTitle: { create: "Novo motivo de impeditivo", edit: "Editar motivo de impeditivo" },
      dialogDescription: "A categoria diz se o impeditivo dependia da pessoa.",
      label: "Motivo",
      labelPlaceholder: "Ex.: Aguardando fornecedor",
      category: "Categoria",
      emptyTitle: "Nenhum motivo de impeditivo",
      emptyDirection: "Os impeditivos da daily ficam sem motivo até haver algum cadastrado.",
    },
    ticketPatterns: {
      direction:
        "Aplicados em ordem ao colar a URL do chamado; o primeiro que reconhecer fica com o ID. Em cada padrão vale a captura mais longa da URL.",
      new: "Novo padrão",
      dialogTitle: { create: "Novo padrão de URL", edit: "Editar padrão de URL" },
      dialogDescription: "Expressão regular com um grupo de captura para o ID.",
      label: "Nome",
      labelPlaceholder: "Ex.: Helpdesk — tickets",
      regex: "Expressão regular",
      regexPlaceholder: "Ex.: /tickets/(\\d+)",
      captureGroup: "Grupo de captura",
      captureGroupHelp: "Qual grupo entre parênteses contém o ID. 1 é o primeiro.",
      invalidRegex: "Expressão regular inválida.",
      groupOutOfRange: "A expressão não tem esse grupo de captura.",
      tester: "Testar URL",
      testerPlaceholder: "Cole uma URL de chamado",
      testerResult: "ID extraído:",
      testerPattern: "pelo padrão {pattern}",
      testerNone: "Nenhum padrão ativo reconhece esta URL.",
      testerThis: "Este padrão extrai:",
      testerThisNone: "Este padrão não reconhece a URL.",
      emptyTitle: "Nenhum padrão de URL",
      emptyDirection: "Sem padrão, o ID do chamado é digitado à mão na validação.",
    },
    validation: {
      labelRequired: "Informe o nome.",
      duplicate: "Já existe um item com este nome.",
    },
  },
  period: {
    label: "Período",
    from: "De",
    to: "Até",
    apply: "Aplicar",
  },
  notFound: {
    title: "Página não encontrada",
    direction: "Este endereço não corresponde a nenhuma página do Prontuário. Confira o link ou volte para Hoje.",
    action: "Ir para Hoje",
  },
  pages: {
    today: {
      subtitle: "Quem precisa da sua atenção hoje.",
      emptyTitle: "Nenhum alerta por enquanto",
      emptyDirection:
        "Combinados vencidos, 1:1 atrasados, PDIs parados e dailies não registradas aparecem aqui, ordenados por urgência, assim que houver registros do time.",
    },
    team: {
      subtitle: "Cadastro das pessoas do time, com senioridade, último 1:1 e combinados em aberto.",
      emptyTitle: "Nenhuma pessoa cadastrada",
      emptyDirection:
        "Cada analista cadastrado ganha um perfil com timeline, combinados, 1:1, feedbacks e plano de desenvolvimento.",
    },
    agreements: {
      subtitle: "Compromissos combinados com o time, com responsável, prazo e histórico de reagendamento.",
      emptyTitle: "Nenhum combinado registrado",
      emptyDirection:
        "Combinados nascem em dailies, 1:1 e feedbacks e aparecem aqui com o prazo original, o prazo atual e quantas vezes foram reagendados.",
    },
    dailies: {
      subtitle: "Revisão dos combinados do dia anterior e registro dos novos, por pessoa.",
      emptyTitle: "Nenhuma daily registrada",
      emptyDirection:
        "Ao registrar uma daily, os combinados da anterior e os vencidos entram para revisão automaticamente.",
    },
    settings: {
      subtitle: "Catálogos, limiares e cadastros que alimentam o produto. Toda alteração fica na auditoria.",
    },
  },
  command: {
    title: "Paleta de comandos",
    description: "Busque uma ação ou um registro",
    placeholder: "Buscar pessoa, registro ou ação",
    pickPlaceholder: "Nome da pessoa",
    open: "Abrir a paleta de comandos",
    groups: {
      context: "Para {name}",
      register: "Registrar",
      navigate: "Ir para",
      people: "Pessoas",
      recent: "Combinados recentes",
      pick: "{action} — com quem?",
    },
    actions: {
      daily: "Nova daily",
      agreement: "Novo combinado",
      validation: "Validar prioridade",
      oneOnOne: "Registrar 1:1",
      feedback: "Dar feedback",
      note: "Anotação",
      watch: "Nova observação",
      openProfile: "Abrir perfil",
    },
    forPerson: {
      oneOnOne: "Registrar 1:1 com {name}",
      feedback: "Dar feedback para {name}",
      agreement: "Novo combinado com {name}",
      note: "Anotação sobre {name}",
    },
    choosePerson: "escolher a pessoa",
    searching: "Buscando nos registros",
    noResults: "Nada encontrado para “{query}”",
    tooShort: "Digite ao menos 2 letras para buscar nos registros",
    seeAll: "Ver todos os resultados de “{query}”",
    back: "Voltar",
    hint: "Enter abre · Esc fecha",
  },
  search: {
    title: "Busca",
    subtitle: "Pessoas, 1:1, feedbacks, anotações, combinados e o resto da timeline. Sem acento e por radical: “relatorio” acha “relatórios”.",
    placeholder: "Buscar nos registros",
    label: "Termo da busca",
    submit: "Buscar",
    type: "Tipo",
    allTypes: "Todos os tipos",
    period: "Período",
    periods: { "30d": "30 dias", "3m": "3 meses", "6m": "6 meses", "12m": "12 meses", all: "Tudo" },
    kinds: {
      person: "Pessoas",
      oneOnOne: "1:1",
      feedback: "Feedbacks",
      note: "Anotações",
      agreement: "Combinados",
      other: "Outros registros",
    },
    count: { one: "1 resultado", other: "{count} resultados" },
    showing: "mostrando {shown} de {total}",
    seeType: "Ver só {kind}",
    emptyQuery: "Digite um termo para buscar",
    emptyQueryDirection: "A busca procura no texto inteiro dos registros, não só no título. Registros privados ficam fora para quem tem acesso de leitura.",
    emptyTitle: "Nada encontrado",
    emptyDirection: "Tente outra palavra, um período maior ou todos os tipos.",
    elapsed: "{ms} ms",
    private: "Privado",
  },
  table: {
    moreDetails: "Mais detalhes",
    lessDetails: "Menos detalhes",
    loading: "Carregando registros",
    errorTitle: "Não foi possível carregar os registros",
    emptyTitle: "Nenhum registro",
    selectedRow: "Linha selecionada",
  },
  severity: {
    /** Degrau "laranja" da escala graduada (attention + strong). */
    attentionStrong: "Atenção forte",
  },
  deadline: {
    noDueDate: "Sem prazo",
    onTrack: "Em dia",
    dueToday: "Vence hoje",
    dueInDays: "Vence em {days} dias",
    dueTomorrow: "Vence amanhã",
    overdueOneDay: "Vencido há 1 dia",
    overdueDays: "Vencido há {days} dias",
    probablyForgotten: "Provavelmente esquecido",
  },
  sparkline: {
    summary: "{count} pontos, de {first} a {last}",
    empty: "Sem dados no período",
  },
  uiLab: {
    title: "UI Lab",
    subtitle: "Referência visual obrigatória. Todo componente novo nasce aqui antes de entrar numa tela.",
    states: {
      default: "Padrão",
      hover: "Hover",
      focus: "Foco",
      selected: "Selecionado",
      disabled: "Desabilitado",
      loading: "Carregando",
      empty: "Vazio",
      error: "Erro",
      compact: "Compacto",
    },
    showToast: "Mostrar aviso",
  },
} as const;

export const enumLabels = {
  memberStatus: {
    ACTIVE: "Ativo",
    ON_LEAVE: "Afastado",
    OFFBOARDING: "Em desligamento",
    INACTIVE: "Inativo",
  },
  role: {
    OWNER: "Gestor",
    MANAGER: "Gestor de time",
    VIEWER: "Leitura",
  },
  /** Nível de acesso ao time (P22, TeamAccess). */
  teamAccessLevel: {
    MANAGER: "Gestor",
    VIEWER: "Leitura",
  },
  visibility: {
    PRIVATE: "Privado",
    SHARED: "Compartilhado",
  },
  feedbackCategory: {
    RECOGNITION: "Reconhecimento",
    DEVELOPMENT: "Desenvolvimento",
    BEHAVIOR: "Comportamento",
    TECHNICAL: "Técnico",
    PERFORMANCE: "Desempenho",
    FORMAL: "Formal",
  },
  agreementOrigin: {
    DAILY: "Daily",
    ONE_ON_ONE: "1:1",
    FEEDBACK: "Feedback",
    MEETING: "Reunião",
    INCIDENT: "Ocorrência",
    MANAGER: "Gestor",
    OTHER: "Outra",
  },
  agreementPriority: {
    LOW: "Baixa",
    NORMAL: "Normal",
    HIGH: "Alta",
  },
  checkinOutcome: {
    DONE: "Feito",
    PARTIAL: "Parcial",
    NOT_DONE: "Não feito",
  },
  metricDirection: {
    HIGHER_IS_BETTER: "Maior é melhor",
    LOWER_IS_BETTER: "Menor é melhor",
  },
  blockerCategory: {
    EXTERNAL: "Externo",
    INTERNAL: "Interno",
    CAPACITY: "Capacidade",
  },
  agreementStatus: {
    OPEN: "Aberto",
    IN_PROGRESS: "Em andamento",
    DONE: "Concluído",
    CANCELLED: "Cancelado",
  },
  devReturnCategory: {
    ANALYST: "Analista",
    PROCESS: "Processo",
  },
  validationOutcome: {
    MAINTAINED: "Mantida",
    RAISED: "Elevada",
    LOWERED: "Rebaixada",
    RETURNED: "Devolvida",
  },
  planStatus: {
    DRAFT: "Rascunho",
    ACTIVE: "Ativo",
    PAUSED: "Pausado",
    DONE: "Concluído",
    CANCELLED: "Cancelado",
  },
  actionStatus: {
    OPEN: "Aberta",
    IN_PROGRESS: "Em andamento",
    DONE: "Concluída",
    CANCELLED: "Cancelada",
  },
  /** Etiqueta mono do tipo de registro na timeline (DESIGN.md). */
  timelineEventType: {
    DAILY: "Daily",
    FEEDBACK: "Feedback",
    ONE_ON_ONE: "1:1",
    RECOGNITION: "Reconhecimento",
    INCIDENT: "Ocorrência",
    AGREEMENT: "Combinado",
    AGREEMENT_DONE: "Concluído",
    ROLE_CHANGE: "Carreira",
    SENIORITY_CHANGE: "Senioridade",
    DEVELOPMENT: "PDI",
    NOTE: "Anotação",
    WATCH: "Em observação",
  },
  severity: {
    calm: "Em dia",
    attention: "Atenção",
    overdue: "Vencido",
    neutral: "Aberto",
  },
} as const;

type EnumLabels = typeof enumLabels;

export function enumLabel<G extends keyof EnumLabels>(
  group: G,
  value: keyof EnumLabels[G],
): string {
  return enumLabels[group][value] as string;
}

/** Substitui `{chave}` pelos valores informados: fill("Vence em {days} dias", { days: 3 }). */
export function fill(template: string, values: Record<string, string | number>): string {
  return template.replace(/\{(\w+)\}/g, (match, key: string) =>
    key in values ? String(values[key]) : match,
  );
}

/** Escolhe singular ou plural e interpola: plural(labels.attention.overdue, 2, { days: 9 }). */
export function plural(
  forms: { one: string; other: string },
  count: number,
  values: Record<string, string | number> = {},
): string {
  return fill(count === 1 ? forms.one : forms.other, { count, ...values })
}
